app/clients/sms/twilio.py, app/config.py, app/notifications/notifications_sms_callback.py, app/notifications/process_client_response.py, app/notifications/receive_notifications.py, migrations/versions/0306_add_twilio_provider.py, migrations/versions/0306a_increase_phone_number_length.py, tests/app/notifications/test_receive_notification.py
Enabling Twilio as a provider, and adding lots of tests around receiving inbound SMS from Twilio
=> Two way communication

Makefile, app/models.py, tests/app/db.py, tests/app/test_model.py, tests/app/v2/notifications/test_get_notifications.py
department-of-veterans-affairs/notification-api#239
=> Add recipient identifiers to query endpoint

requirements-app.txt, requirements.txt
and bump dependencies due to pip-freeze.
=> Remove awscli-cwlogs

app/celery/process_ses_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py
* Also refactor test to mock models to decouple from db
Co-authored-by: Emily Wu <ewu@thoughtworks.com>
=> [#381] Add test for invoking send complaint to vanotify in process ses task

.talismanrc, app/celery/nightly_tasks.py, app/celery/service_callback_tasks.py, app/commands.py, app/dao/service_callback_api_dao.py, app/dao/users_dao.py, app/models.py, app/notifications/process_client_response.py, app/schemas.py, app/service/callback_rest.py, app/service/service_callback_api_schema.py, migrations/versions/0329_notification_status.py, requirements-app.txt, requirements.txt, tests/app/celery/test_nightly_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/dao/test_service_callback_api_dao.py, tests/app/db.py, tests/app/notifications/test_process_client_response.py, tests/app/service/test_callback_rest.py, tests/app/service/test_schema.py, tests/conftest.py
[notification-api#468] define which statuses should trigger service callback
=> [notification-api#468] Configure which notification statuses trigger callbacks

app/celery/lookup_recipient_communication_permissions_task.py, app/notifications/process_notifications.py, tests/app/celery/test_lookup_recipient_communication_permissions_task.py, tests/app/notifications/test_process_notifications.py
Co-authored-by: Ling Tran <ltran@thoughtworks.com>
=> [#517] Refactors lookup_recipient_communication_permissions task parameters

app/template/rest.py, app/template/template_schemas.py, app/user/rest.py, tests/app/template/test_rest.py
Co-authored-by: Anita DeWitt <adewitt@thoughtworks.com>
Co-authored-by: Phil Herbert <pherbert@thoughtworks.com>
=> [department-of-veterans-affairs/notification-ui#33] Checking for user id from current_user if created_by not passed into request

app/models.py, migrations/versions/0337a_rate_limit_interval.py
Co-authored-by: Anita DeWitt <adewitt@thoughtworks.com>
=> [#564] Refactor database migration

README.md, ci/Dockerfile, ci/Dockerfile.local, ci/Dockerfile.test, ci/Dockerfile.userflow
This is for [vanotify-team issue 126](https://github.com/department-of-veterans-affairs/vanotify-team/issues/126).  These changes document the changes I made for #598.  There are no code changes.
=> Update README.md to describe the Docker image dependencies and upgrade process

scripts/postman/notification-api.postman_collection.json
I tested manually in Postman.  I had to re-import the collection for Postman to reflect the changes.
=> Corrected template variables in the collection

app/oauth/jwt_manager.py, app/oauth/rest.py, tests/app/oauth/test_rest.py, tests/app/test_route_authentication.py
https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-team/170
=> Fix Login issue when 10+ services are assigned to user

.github/workflows/lambda-functions.yaml, lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
VeText Twilio Incoming Messages Lambda Handler
=> Vetext twilio incoming forwarder lambda

app/template/rest.py
Just a small change to make sure the "onsite_notification" value can be updated on templates.
=> Fixing template updates for onsite_notification - Bugfix/715

app/__init__.py, app/celery/lookup_va_profile_id_task.py, app/celery/onsite_notification_tasks.py, app/config.py, app/notifications/process_notifications.py, app/v2/notifications/post_notifications.py, app/va/va_onsite/__init__.py, app/va/va_onsite/va_onsite_client.py, cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-beat-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json, ci/.docker-env.example, tests/app/conftest.py, tests/app/db.py, tests/app/notifications/test_process_notifications.py, tests/app/test_config.py, tests/app/va/va_onsite/test_va_onsite_client.py
Adding Onsite Notifications to Celery Queue for Issue #624
=> Onsite notification code changes - 624-2

lambda_functions/user_flows/steps.py, lambda_functions/user_flows/test_retrieve_everything.py, user_flows/steps.py
#727
I updated the jwt code related to user flow tests to be compatible with PyJWT>=2.0.0, which modified the jwt.encode function to return a string rather than a bytes array.  I also deleted some code and made other code more readable.
The side-by-side diff view is helpful for this PR.
Relevant documentation:
https://pyjwt.readthedocs.io/en/stable/changelog.html
https://en.wikipedia.org/wiki/JSON_Web_Token#Use
=> Fix user flows test failure

app/va/vetext/client.py
=> Added logging for push calls

requirements-app.txt, requirements.txt
[vanotify-team 386](https://github.com/department-of-veterans-affairs/vanotify-team/issues/386)
Issue: Preview has been loaded in iframe and clicking the link load the new page inside entire iframe. 
Expected behavior: Clicking link should open the page in new tab
=> Fix Links in Template Preview iframe

.github/workflows/build-manual.yaml, .github/workflows/deployment.yaml, .github/workflows/dev-ci.yaml, .github/workflows/perf-build-deploy.yaml, .github/workflows/production-trigger.yaml, .github/workflows/tagging.yml, app/models.py, migrations/versions/0350_add_sms_sender_service_id.py
[#746](https://github.com/department-of-veterans-affairs/notification-api/issues/746)
Added sms_sender_service_id column to service_sms_senders table.
=> VEText Migration - DB update to support message service id

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py, tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Added code to close the connection to VeText after the request has been made.  Also includes, re-organization of other related code so that exceptions related to the request were handled inside the method.  Updated the tests accordingly.
=> Vetext two way lambda close http connection

app/va/va_onsite/va_onsite_client.py
#746 
Branch: bug/746
This is a quick fix to make sure we aren't getting errors when trying to report logs for Onsite notifications.
=> 746 - Fixed the potential issue with the Onsite logger

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py, tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
#755 - Updated Vetext Incoming Forwarder Lambda code to incorporate a dead letter queue
=> #755 vetext reverse proxy dead letter queue

.github/workflows/dev_deploy.yml, .github/workflows/release_trigger.yml, .github/workflows/tag_trigger.yml
No ticket. Just a quick update per @k-macmillan request to have the output in the steps have more information in there.
=> Dev output update

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py, tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
#812 
minor changes to address the 502 errors that Twilio has been logging.
=> #812 explicit timeout vetext forwarder lambda

app/celery/lookup_va_profile_id_task.py, tests/app/celery/test_lookup_va_profile_id_task.py
Callback method called when a failure occurs during the lookup process.
Fixes #837 (Enhance Callback When Person Lookup Fails)
=> #837 Enhance Callback method

README.md
Fixes # (issue)
[#676](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/676)
=> #676: Restore directions for developing in a local environment

lambda_functions/va_profile/va_profile_opt_in_out_lambda.py, tests/lambda_functions/va_profile/test_va_profile_integration.py
These changes support reading JWT related certificates from disk (via a lambda layer), obtaining the ALB certificate chain from ACM, and obtaining the ALB certificate's private key from SSM Parameter Store.  These changes get PUT requests, with mTLS, working for VA Profile integration.
Fixes #836 
See [the CloudWatch log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fproject-dev-va-profile-opt-in-out-lambda/log-events/2022$252F10$252F05$252F$255B$2524LATEST$255D342e0228f0b2410da5786072c2ede75e).
=> #836 make va_profile_opt_in_out lambda read certificates from lambda layers and ACM

.talismanrc, app/notifications/validators.py
Daily limit warning changed to a percentage of the limit, logger message updated to reflect percentage, binary representation casted to int.
Fixes #768  (Daily limit warning not sufficient and incorrect format)
=> #768 Daily limit warning not sufficient and incorrect format

.talismanrc, lambda_functions/va_profile/va_profile_opt_in_out_lambda.py, tests/lambda_functions/va_profile/test_va_profile_integration.py
These changes fix an issue identified at the outset of QA testing, as described in the ticket.
Fixes #871.
I updated a unit test to reflect the changes in the lambda handler.
=> Profile integrations does not correctly identify a request for QA testing

lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
I added additional logging statements and changed the level of existing statements.  The goal is that CloudWatch tells a complete story for a given request.
Closes #876.
=> VA Profile integration logging changes

.github/workflows/lambda-functions.yml
Lambdas environments not unique issue is fixed by naming the virtual environments differently for each lambda.
Fixes #831
=> #831 Fix BUG: Lambdas Environments not Unique

lambda_functions/va_profile/requirements-lambda.txt, requirements-app.txt, requirements.txt, requirements_for_test.txt
There is no ticket associated with this PR.  I upgraded the requirements files after rebuilding the app and test images.  All unit tests passed locally.
=> Requirements upgrades after rebuilding the app and test images.

documents/openapi/openapi.yaml
Notification Endpoint API Doc update, response examples for `sms` and `email`.
Fixes #860 
=> 860 Update API Docs: Notification Endpoint

app/inbound_number/inbound_number_schema.py, app/models.py, documents/openapi/openapi.yaml, migrations/versions/0353_inbound_number_add_fields.py, tests/app/dao/test_inbound_numbers_dao.py, tests/app/db.py, tests/app/inbound_number/test_rest.py
These changes add two new fields to the InboundNumbers table, create an associated migration, update the RESTful endpoints, update the JSON schema used for validation, and update associated unit tests.
I began updating openapi.yaml before realizing that it requires significant work and opened #965 to complete this task.
Fixes #932
=> #932 Two-way SMS Infrastructure: Add two fields to the InboundNumbers table, and update the API.

app/celery/onsite_notification_tasks.py, app/va/va_onsite/va_onsite_client.py
Formatted log messages with old printf style
Fixes [#482](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-team/482)
=> #482: Format log message with old printf style

.github/workflows/dev_deploy.yml, .talismanrc, app/celery/process_pinpoint_receipt_tasks.py, app/celery/process_ses_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py
This is a small change to add status reasons in places where they are still missing. (hard and soft "bounce")
Fixes #935
Send a message that causes a "bounce" and check to make sure the notification `status_reason` is updated.
=> #935 Missing Status Reasons Updates

.talismanrc, lambda_functions/two_way_sms/two_way_sms_v2.py
Make log levels consistent with the team's [logging policy](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/logging_policy.md).  Revise exception handling and comments.
#923
=> Make log levels consistent with the team's definitions.  Revise excep

.github/workflows/tests.yaml, ci/docker-compose-test.yml, lambda_functions/two_way_sms/two_way_sms_v2.py, tests/lambda_functions/two_way_sms/test_two_way_sms_v2.py
[923](https://github.com/department-of-veterans-affairs/notification-api/issues/923)
Hotfix to apply VeText auth token for post authentication to VeText endpoint.
=> added retrieval of auth token for vetext and added to header

app/celery/reporting_tasks.py, app/config.py, app/dao/fact_billing_dao.py, tests/app/dao/test_ft_billing_dao.py
These changes add 2 fields to the Notification table query used for nightly billing stats and updates the affected unit test.
I also cleanup up the code a bit.  It's the same couple of minor changes applied in a bunch of places.
Deployed: https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3859329247
#1022
=> #1022 Update nightly billing upload with sender_id and sender.

.talismanrc, app/celery/reporting_tasks.py, app/dao/fact_billing_dao.py, app/service/rest.py, tests/app/celery/test_reporting_tasks.py, tests/app/dao/test_ft_billing_dao.py, tests/app/service/test_api_key_endpoints.py
Added a unit test to catch an issue encountered during this upgrade. Updated the code to work with the new changes.
=> Fix billing error for flask upgrade

Makefile, requirements-app.txt, requirements.txt
It was identified that there is a [fix for the import error](https://github.com/benoitc/gunicorn/pull/2581). This change locks us to [that point](https://github.com/benoitc/gunicorn/tree/6a8ebb4844b2f28596ffe7421eb9f7d08c8dc4d8) in the repository.
This allows us to be up to date with `eventlet` as well.
Speedy deploy
Sent myself an email:
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
=> gunicorn Fix for Eventlet

app/celery/process_delivery_status_result_tasks.py, app/celery/service_callback_tasks.py, tests/app/celery/test_service_callback_tasks.py
#1201 
The Delivery Status handler was not including the original delivery status payload in the service callback request.  
- Created service callback with "include_provider_payload" = true and verified that provider payload came through with service callback
- Updated service callback with "include_provider_payload" = false and verified that provider payload DID NOT came through with service callback
=> #1201 Hotfix twilio delivery status payload

.talismanrc, app/authentication/auth.py, app/callback/webhook_callback_strategy.py, app/celery/letters_pdf_tasks.py, app/clients/sms/firetext.py, app/clients/sms/mmg.py, app/errors.py, app/notifications/notifications_sms_callback.py, app/oauth/rest.py, app/template_folder/rest.py, app/user/rest.py, app/v2/errors.py, app/v2/notifications/post_notifications.py, app/v2/notifications/rest_push.py, app/va/va_profile/va_profile_client.py, app/va/vetext/client.py, lambda_functions/two_way_sms/two_way_sms_v2.py, lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py, requirements.txt
The most important change in this PR is updating requirements.txt to use the newest commit in the master branch of notification-utils to incorporate the fix that eliminates all of the logged KeyError, AttributeError, etc. exceptions.  The cause of those exceptions was an improper implementation of custom log formatters.  See [notification-utils PR 118](https://github.com/department-of-veterans-affairs/notification-utils/pull/118).
Before I figured out the formatter problem, I proceeded under the assumption that the errors stemmed from incorrect string substitution in the logging message.  These changes primarily contain tweaks to logging statements that I made while auditing the code.  Most of the changes are switching from "format" based string substitution to the C-style %-based …
=> #1222 Remediating logging calls.

app/callback/webhook_callback_strategy.py
I changed a requests timeout value from 60 (seconds) to the tuple (3.05, 1).  There is no associated ticket.
Timeout value change
I ran unit tests.  I don't think it's necessary first to deploy this change.
=> Changing a requests timeout value.

app/va/mpi/mpi.py
[#970](https://github.com/department-of-veterans-affairs/vanotify-team/issues/970)
Running the QA suit occasionally fails due to read timeouts in the lower environments. This change should reduce those failures.
=> 970 MPI Read Timeout

.github/workflows/deployment.yml, .github/workflows/release.yml, .github/workflows/release_trigger.yml
This PR addresses an issue where the "pre-release" trigger for GitHub Actions is not working as expected in our `.github/workflows/release_trigger.yml` file. To mitigate this issue, we're changing the trigger event from `release` and `pre-release` to `published`. This change aims to automate the deployment to staging whenever a pre-release is published, eliminating the need for manual deployment.
The only way to accurately test this change is by merging it to the master branch and then creating a test pre-release. Hence, it requires a fast-track review and approval process to validate the fix.
#1214
Due to the nature of this change, the only way to verify the fix is by merging this PR into the master branch, creating a pre-release, and publishing it to trigger the GitHub Actions workflow. …
=> #1214 Fix Pre-release Trigger for GitHub Actions

.github/ISSUE_TEMPLATE/bug-report-template.md, .github/ISSUE_TEMPLATE/spike-template.md, .github/ISSUE_TEMPLATE/story-template.md, .github/pull_request_template.md
Update the issue templates.  There is no ticket for this.
N/A.  These are documentation changes.
=> Update issue templates

app/celery/common.py, app/celery/contact_information_tasks.py, app/celery/lookup_recipient_communication_permissions_task.py, app/celery/lookup_va_profile_id_task.py, app/celery/provider_tasks.py
This is just an addition to allow for logging if we are retrying. It's good information to have if we're retrying and now something we can track.
Unit tested, [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5673058696/job/15373671321#step:4:8), userflows tested, regression tested.
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] Any dependent changes have been merged and published in downstream modules~
=> Autoretry Logging Update

.github/workflows/build.yml, .github/workflows/db-downgrade.yml, .github/workflows/deployment.yml, .github/workflows/twistlock.yml, .github/workflows/update-datadog-image.yaml
We have identified an issue in our pipeline where the Docker is not masked when logging into ECR. 
Address issue outlined in team repo. 
The changes have been tested by executing the workflow and ensuring that Docker is masked during the ECR login process. Further tests were conducted to ensure that the masking does not interfere with other functionalities.
=> Docker ECR Login action

.github/workflows/dev_deploy.yml, .github/workflows/regression-public.yml, bar
The goal of this PR is to trigger the QA suite to run against private endpoints whenever a deploy to staging or perf occurs.  As well.
issue #1326
How has this been tested? (e.g., screenshots, links to deployment, regression test results) to demonstrate the functionality or fix: e.g. Tested locally, Tested as a GitHub action, etc.
with this command:  
```
gh workflow run -r 1326-qa-suite -F ref=1326-qa-suite -F environment=perf dev_deploy.yml
```
and can be tested again with the same command if you have the GH cli locally. 
Notes:
- since the last run, the name of the workflow has changed from  pull-and-run-container  to  run-QA-suite
=> #1326 Run QA Suite on Deploy to Dev action

app/platform_stats/rest.py
This PR removes two unneeded TODO comments.
- the first TODO concerns adding defaults or request validation to the method get_usage_for_all_services() and has been determined by the team to be unnecessary since as written, the code tests that the given dates are in the same fiscal year and that the start_date is earlier than the end_date. If not, or if either date is None, InvalidRequest is raised. This seems like an appropriate implementation. 
- the second TODO concerns adding costs for email and has been determined by the team to not be needed because  costs are not an input to determining which provider to use …
=> #886 remove unneeded TODOs

.github/workflows/regression-public.yml
Updated the regression tests to run the full regression.
issue #1326
Tested by deploying and running
=> #1326 - Run All QA Suite Tests

.github/workflows/dev_deploy.yml
This is a simple name change to the Deploy to Dev action, based on the team request. 
- This is simply a string change to a title, there is no need to test
=> Deploy to Dev - name change

app/celery/process_pinpoint_receipt_tasks.py, app/notifications/aws_sns_status_callback.py, tests/app/celery/test_process_pinpoint_receipt_tasks.py
This change is to fix the status being set to "sent" instead of "delivered" when sms messages are successfully sent from our endpoints.
issue #1449 
Log message and notification details of notification sent before change
```
[2023-09-25 15:41:41,524: INFO/ForkPoolWorker-4] Pinpoint callback return status of sent for notification: 6acf1167-90ee-47b4-bd6e-03a7630d8d85
```
```json
{
"billing_code": null,
"body": "This is a sample SMS without a variable in it. Messages longer than 160 …
```
=> #1449 - BUG: Pinpoint Successful Status Sent vs Delivered

app/service/rest.py, tests/app/service/test_rest.py
Remove letter-contact routes and associated route tests.  I started to delete dao code, but that caused errors.  Letter dao code should be revisited after all the letter route deletion PRs are merged.
#1158 
=> #1158 Remove letter-contact routes

documents/openapi/openapi.yaml
These changes eliminate console errors (bottom left) visible when loading our openapi.yml file into the [newer Swagger Editor](https://editor-next.swagger.io/).  These problems are all improper use of the "items" attribute for data that is not an array.  I changed the spec to reflect what the code actually returns.
A different error is displayed in the top right if you load the file into the [older Swagger Editor](https://editor.swagger.io/).  According to the Json schema docs, [const](https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values) can be used for any attribute, and it doesn't request also specifying "type".  I removed the "type" specifier thinking that was the problem in the older editor, but it didn't fix it.  I'm thinking the older editor is …
=> More Swagger corrections

.github/workflows/tag_trigger.yml, README.md
issue #1442 
Adds Run regression to the end of the Tag Push to Perf action. 
A corresponding change was made to the Readme so that GitHub actions actually recognizes a change has been made.
- Due to the way that this action works, the changes need to be deployed to master before a tag can be cut and pushed, to see …
=> #1442 add regression to tag trigger

.github/workflows/dev_deploy.yml, .github/workflows/prerelease_trigger.yml, .github/workflows/regression-public.yml, .github/workflows/tag_trigger.yml
The business need for this ticket is to automatically trigger and run a full test suite against the staging environment upon a pre-release of the notification-api, ensuring code reliability before it reaches production.
PR also  renames the job `run-QA-suite` to `run-qa-suite` in all 4 files using it.
issue #1327
- This needs to be merged into master to test. Testing is a sending a pre-release to staging. 
The rollback plan is to revert if the action doesn't work as intended.
- Noting …
=> #1327 Run QA suite on staging pre-release trigger

.github/workflows/build.yml, .github/workflows/db-downgrade.yml, .github/workflows/deploy_lambda_dev.yml, .github/workflows/deployment.yml, .github/workflows/dev_deploy.yml, .github/workflows/lambda-functions.yml, .github/workflows/load-test-email-delivery-time.yaml, .github/workflows/load-test-sms-response-time.yaml, .github/workflows/regression-public.yml, .github/workflows/tests.yaml, .github/workflows/twistlock.yml, .github/workflows/update-cached-image.yaml, .github/workflows/update-datadog-image.yaml, .github/workflows/user_flows.yml
This combines the changes in the 3 dependabot PRs for updating Github actions.
- [configure-aws-credentials v2.2.0 to v4.0.1](https://github.com/department-of-veterans-affairs/notification-api/pull/1485)
- [actions/checkout v3 to v4](https://github.com/department-of-veterans-affairs/notification-api/pull/1446)
- [setup-buildx-action v2 to v3](https://github.com/department-of-veterans-affairs/notification-api/pull/1446)
issue #1472 
=> #1472 Update Dependencies - Github Actions

.github/workflows/dev_deploy.yml, cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/dev/vaec-db-downgrade-task-definition.json, cd/application-deployment/dev/vaec-db-migrations-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-db-downgrade-task-definition.json, cd/application-deployment/staging/vaec-db-migrations-task-definition.json
Updated cpu/mem for dev and staging. Added a helper to the setup-env to allow us to identify which environment we're sending this to without having to dig for it.
issue N/A
Deployed to dev and staging.
All healthy
API service
All healthy
=> Task CPU and Memory Update

app/celery/v3/notification_tasks.py
These changes further refine the implementation for POST /v3/notifications/* by adding Celery task retry logic.
- [Celery retry docs](https://docs.celeryq.dev/en/stable/userguide/tasks.html#retrying)
issue #1361
I don't know of a good why to test this.  Unit tests could use a mock to raise an exception, but that won't result in a retry because the code under test isn't actually running as a task when called from unit tests.
=> #1361 v3 basic send logic (part 2)

lambda_functions/two_way_sms/two_way_sms_v2.py
Just added destination number logging so we can identify use case through our logs. The value looked up must be a dictionary to make it that far, so this has no possibility of causing errors. 
issue N/A
This is a logging addition. There is no testing.
Line 195 ensures it is a dictionary before we use it:
And even then, a safe lookup is performed (using `get` in the logger instead of `[]`).
=> Two Way SMS Logging Hotfix

app/celery/process_delivery_status_result_tasks.py, app/celery/process_pinpoint_receipt_tasks.py, app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/service/test_rest.py
These changes are in response to Twilio messages getting stuck in "sent" status. These changes should make it less likely that the messages will be stuck when updating statuses. 
issue #1488 
=> #1488 BUG: Twilio delivered messages getting stuck in sent

app/models.py, migrations/versions/0365_add_notification_failures.py
Because we are validating certain items after returning a 202 Accepted from the v3 POST routes, we need to be able to handle validation failures for certain instances with a new table in PostgreSQL
issue [#1512](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1512)
Migrations (up and down) were run locally to verify the change.
=> #1512 notification failures table

cd/application-deployment/perf/vaec-celery-beat-task-definition.json
This is a hotfix to move the task definition variables into the correct location.
issue #N/A
[Deployed ](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6906525342)correctly.
=> Fixed Parameter Location for Perf

documents/openapi/openapi.yaml
We want to add the public base URLs for the API endpoints such that clients can see what they are via the Portal. This PR Updates the [API documents](https://github.com/department-of-veterans-affairs/notification-api/tree/master/documents/openapi) to include both private and public URLs, an explanation of when to use each, and includes the Perf environment.
issue #1377
Please provide relevant information and / or links to demonstrate the functionality or fix. (e.g. …
=> #1377 - Add public endpoints to OpenAPI swagger document

requirements.txt
This is a hotfix to upgrade werkzeug from version 2.3.7 to version 2.3.8, which fixes a vulnerability that makes Safety fail.  More information [here](https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-2-3-8).  There is no ticket.
- Safety and unit tests pass
- [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7011157225)
- [regressions pass](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/7011273102)
=> Hotfix to upgrade werkzeug

Makefile, requirements-app.txt
This is just a quick fix to ignore the flagged pypdf version since we aren't using it anyway.
issue # N/A
=> Ignore pypdf

app/config.py, cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json
Changed system to utilize a protected admin username that is maintained in AWS for added security.
issue N/A
Requests work with the new client secret and admin.
=> Updated to use protected admin user name

Makefile, requirements-app.txt, requirements.txt
Updating requirements.txt, requirements-app.txt and Makefile with as current as possible libraries. 
issue #(issue)
Ran regression tests in Dev. 
(https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/7185890153)
=> #1552 Updating requirements.

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
Adding a logging default and exception handling if envar was incorrectly set. I don't like it but here it is. 
issue #1189
Just logging to allow for testing for 1189.
=> #1189 adding info logging

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
This is a quick hotfix to fix the 4xx errors we were seeing when we deployed to prod.
issue #(issue)
=> Hotfix Vetext Forwarder Params

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
The client was incorrectly set to use `us-west-1`. Removed region from all client invocations. 
boto3 uses the default context. It is aware of what region it is in. We do not need to specify that information unless we intend to use a _different_ region.
issue N/A
=> HOTFIX Update boto3 Client Invocation

app/celery/service_callback_tasks.py, app/va/va_profile/va_profile_client.py, app/va/vetext/client.py, lambda_functions/two_way_sms/two_way_sms_v2.py, lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py, tests/app/va/vetext/test_client.py
Identifying actual errors is quite difficult because the logs are littered with expected exceptions. These tend to happen with `requests` module POST requests that resulted in exceptions and log the failure with `logger.exception(e)`. This PR replaces some of them with qualified logging statements. 
Additionally, explicitly created exception block for `ConnectionTimeout` because it was falling to a generic catch, but we expect those to always be a retry. Explicit is better than implicit in this case. Lambda changes are only logging changes.
issue N/A
All unit tests pass. [Deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7400707482). [Regression tests](https://github.com/department-of-veterans-affairs/notification …
=> HOTFIX - Cleaned Loggers and Exceptions

requirements-app.txt
Adds cachetools to requirements-app.txt for local builds. Does not affect deployed applications.
issue N/A
This is a local-only change. Ran locally, works.
=> [BUG] cachetools Local Requirements

.github/workflows/run-regression.yml
issue #1526
The issue is that we attempted to use the `environment` type, and we need to change it back to string for this use case. 
To address this error:
```
Invalid workflow file: .github/workflows/tag_trigger.yml#L50
The workflow is not valid. In .github/workflows/tag_trigger.yml (Line: 50, Col: 11): Error from called workflow department-of-veterans-affairs/notification-api/.github/workflows/run-regression.yml@008dcb8075bed901180052b8ab56c495d6d7e84a (Line: 9, Col: 15): Unexpected value 'environment'
```
How has this been tested? (e.g. Unit tests, Tested locally, Tested as a …
=> #1526 - hotfix for environment type

.github/workflows/prerelease_trigger.yml, README.md
issue #1526 
This was a simple bug -- had to adjust the regression to actually depend upon the existing prerelease job!
[Here is a simple test of the bug](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7548031914/job/20549269177)
=> #1526 - bug fix for prerelease job dependency

README.md
issue (N/A)
This is just a quick update to link to the proper folder for the postman collection in the readme.
=> Update Readme Postman Link

app/va/mpi/mpi.py
issue #1618 
This PR removed the hard-coded cipher list that was used to connect to MPI in Production and creates a more dynamic list while just adding the additional cipher needed for that connection. This will improve ensure future connectivity and that our platform remains secure.
=> #1618 Remove Hard-coded Cipher List for MPI Connection

app/celery/process_ses_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py
Discussion with AWS revealed that Hard and Soft bounce SES results should be treated as the final state of an email request, overwriting any `delivered` status. Soft bounces can and should be retried. Retrying is outside the scope of this ticket/bugfix. 
Updated the `process_ses_results` method to handle bounces rather than sending them downstream to `notifications_dao._update_notification_status`. 
issue #1630
Unit tested locally. Added extra test parameterization to two tests and made a 3rd, parameterized test.
- Deployed & regression [tested](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7837245214)
=> #1630 [Bugfix] Bounce Handling

app/va/mpi/mpi.py, tests/app/complaint/test_complaint_rest.py
issue N/A
This is a quick hotfix to fix the dynamic cipher list for our connection in the lower environments. 
=> Hotfix Cipher List

ci/Dockerfile
This is a revision to install, and later remove, openssl on the Docker image to be able to run the VA CA installation script.  Before these changes, running scripts/import-va-certs.sh while building Dockerfile was producing this output:
```
> [10/11] RUN bash scripts/import-va-certs.sh   && apk del --no-cache wget:
3.237 sh: openssl: not found
3.238 sh: openssl: not found
3.238 sh: openssl: not found
3.239 sh: openssl: not found
3.239 sh: openssl: not found
3.240 sh: openssl: not found
3.240 sh: openssl: not found
3.241 sh: openssl: not found
3.241 sh: openssl: not found
3.242 sh: openssl: not found
```
issue #1043
=> #1043 Revision for openssl

.github/ISSUE_TEMPLATE/notify-dependency-update-template.md
Update the issue template for a routine dependency upgrade.
issue # N/A
=> Update the issue template for a routine dependency upgrade.

Makefile, app/celery/common.py, app/celery/provider_tasks.py, scripts/run_tests.sh, tests/app/celery/test_provider_tasks.py, tests/app/dao/test_fact_notification_status_dao.py, tests/app/delivery/test_send_to_providers.py
We have been retrying on `InvalidPhoneErrors` raised when calling the utils repo. This PR captures this as a distinct exception and marks it as permanent failure, with a `status_reason` that specifies the invalid phone number.
This was intentionally not added to the NonRetryableException catch because that is intended for celery retries being exceeded. Added a comment that NonRetryableException is a celery exception raised with too many retries.
Found duplicate call to function in a unit test, removed it. Temporarily ignored jinja2 issue.
issue N/A
New unit test was written. A current unit test was amended to include a test for this new exception catch.
[Deployed, passed unit tests & regression …
=> [Hotfix] Remove InvalidPhoneError From Automatic Retries

.github/ISSUE_TEMPLATE/lambda-dependency-update-template.md
issue #(issue)
This PR adds a new template for the regular dependency update for lambdas.
=> Add Lambda Dependency Update Template

README.md
Updated README.md to cover new `requirements.txt` vs `requirements-app.txt`.
issue N/A
N/A
=> Updated README With New Requirements File Handling Instructions

.github/ISSUE_TEMPLATE/lambda-dependency-update-template.md
issue #(issue)
This is just adding the necessary information to the template so it shows up in zenhub as a selectable template.
=> Add Header Block so Template Shows in Zenhub

.github/workflows/dev-tests.yml, .talismanrc
Poetry requires a very different setup from a pip install. Since the two are incompatible and I would like to be able to test any branch at any time rather than only on push to master, this action has been made.
The script is not important at this time, but should be correct. Ticket #1665 will update this action as-necessary to ensure proper testing. The action has to exist in `master` for it to be ran though!
issue N/A
N/A This is a new action that is going to go through revisions after it can be tested.
=> Add Dev Test Workflow Dispatch/Call Github Action

.github/workflows/deploy_lambda_dev.yml, .github/workflows/dev_deploy.yml
Updated two GHAs for clarity and reduced chance of failure through a choice dropdown. Added functionality to allow choosing which environment to deploy lambdas to.
issue N/A
Used the action to deploy Staging:
Updated Deploy API to Env:
=> HOTFIX - Updated to Lambda Deploy To Allow Environment

.talismanrc, app/celery/scheduled_tasks.py, app/config.py, cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-beat-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json, tests/README.md, tests/app/celery/test_scheduled_tasks.py
The API contains a Celery Beat task the query DynamoDB for information to send a Comp & Pen notification.  We should only send notifications for "items" (no-sql term; like a row in sql) for which:
1. is_processed is False
2. has_duplicate_mappings is not set or False
3. payment_id is not equal to -1
4. paymentAmount exists
These changes add filters 2, 3, and 4 (above), update outdated information in tests/README.md, enable comp & pen in Perf, and correct a typo in task definition variable names.
issue #1689
@cris-oddball and I collaborated during the development process.  Please see her notes in the ticket.
=> #1689 Update Comp & Pen notification filters

.github/workflows/run-regression.yml
Deploying was not counting the regression test as part of a deploy to a given environment. Added the environment field to the regression suite so we know it is counting against that environment.
issue N/A
Deployed to validate it is working correctly.
Old "complete" [deploy](https://github.com/department-of-veterans-affairs/notification-api/pull/1715):
New deploy complete with [regression run](https://github.com/department-of-veterans-affairs/notification-api/pull/1716):
=> HOTFIX - Added environment to Action

poetry.lock, pyproject.toml
Made an update to the utils repo and updated the API to use the new utils repo. Updated all other dependencies.
Poetry output:
```
• Updating botocore (1.34.64 -> 1.34.78)
• Updating pycparser (2.21 -> 2.22)
• Updating werkzeug (3.0.1 -> 3.0.2)
• Updating boto3 (1.34.64 -> 1.34.78)
• Updating importlib-metadata (6.11.0 -> 7.0.0)
• Updating referencing (0.33.0 -> 0.34.0)
• Updating typing-extensions (4.10.0 -> 4.11.0)
• Updating click-didyoumean (0.3.0 -> 0.3.1)
• Updating ddsketch (2.0.4 -> 3.0.1)
• Updating eventlet (0.35.2 -> 0.36.1)
• Updating kombu (5.3.5 -> 5.3.6)
• Updating opentelemetry-api (1.23.0 -> 1.24.0)
• Updating notification-utils (2.0.1 6044890 -> 2.0.1 3208e26)
• Updating sentry-sdk (1.42.0 -> 1.44.1)
• Updating twilio (9.0.2 -> 9.0.4)
```
issue N/A
Please check the …
=> HOTFIX - Updated Dependencies

app/celery/scheduled_tasks.py, app/config.py, tests/app/celery/test_scheduled_tasks.py
The Comp & Pen Celery scheduled task was updating DynamoDB records one at a time (marking is_processed = True).  This PR modifies that task to use DynamoDB batch writing, instead.
- Corresponding [Infra PR](https://github.com/department-of-veterans-affairs/vanotify-infra/pull/782)
issue #1707
=> #1707 Update Comp & Pen send notification scheduled task to use batch write

app/service/service_senders_schema.py, documents/openapi/openapi.yaml, documents/postman/internal_api_developers/notification-api.postman_collection.json, tests/app/service/test_sms_sender_rest.py
The bug outlined in the ticket was inadvertently fixed at some point.  These changes:
1. Add unit tests to codify the intended (and actual) behavior
2. Add sms_sender_specifics to the schema for the POST route to add a new ServiceSmsSender instance.  This attribute was only part of the update route, which seems like an oversight.
3. Require a valid update request to include at least one attribute to update
4. Update the OpenAPI and Postman docs.  For Postman, this includes setting the default request value of "is_default" to False, rather than True.  For OpenAPI, this includes proper specification of request bodies and refactoring to declare some URL parameters at the "path" level rather than for each verb (GET or POST) of that path.
issue #1215
- [Swagger …
=> #1215 Add unit tests, and improve API documentation, for creating and updating ServiceSmsSender instances

.github/workflows/build.yml, testchange
Reverts department-of-veterans-affairs/notification-api#1743
=> Revert "1727-label-test-pr"

testfile
=> Preparing PR - final test for PR closed trigger

testfile
Reverts department-of-veterans-affairs/notification-api#1762
=> Revert "Preparing PR - final test for PR closed trigger"

testfile
=> Preparing PR - testing closed PR trigger

.github/workflows/dev_deploy.yml, .github/workflows/release_trigger.yml, .github/workflows/run-regression.yml
As a part of the new CI/CD pipeline, we want to automate two smoke tests for the production environment that will replace manually sending an email and an sms notification post-deploy. This PR hooks up the GitHub actions that we use to deploy and regress the code to the Prod release cycle.
**IMPORTANT:**  The regression continues to fail in Dev on MPI lookups. This is expected due to us receiving 401s from our partner. That accounts for the 'failed' deployment.
issue [QA-183](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api-qa/183)
Please provide relevant information …
=> #183 - Add prod smoke test to prod deployments

testfile2
=> testing push payload AND repo level variable value availability

testfile2
=> getting labels from new payload - pr push

testfile2
Reverts department-of-veterans-affairs/notification-api#1776
=> Revert "1727 test"

app/config.py
issue #N/A
This change simply updates the VEText URL for push notification in the Staging environment to the correct URL.
=> Fix VEText Push URL in Staging

testfile
=> testing pipeline with permissions update

app/config.py, testfile
=> 1727 test perf

testfile
=> preparing test with QA - passing github token from cd pipeline

cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-beat-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json
Update task definitions for Comp & Pen by adding values for the DynamoDB table name and ARNs for the service ID and template ID parameters.
I made changes in all 3 of each environment's task definitions because the variable names were already there.  I think, for example, that the DynamoDB table name is only relevant to the "beat task definition", but I'm not going to verify that now.  We have #1711 to audit the task definitions for unnecessary variables.
issue #1750
There's nothing …
=> #1750 Update task definitions for Comp & Pen

cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-beat-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json
My previous PR for this ticket used "value" where "valueFrom" should have been used.  I didn't catch this before because I deployed to Dev prior to the last PR's second commit, which made the changes for Staging and Prod also apply to Dev and Perf.
issue #1750
=> #1750 revision to correct syntax error

app/celery/scheduled_tasks.py, app/config.py, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json
Our monthly Comp & Pen processing implementation results in the execution of a Celery task that sends notifications, and we have a feature flag that must be True for this Celery task to do anything other than immediately return.  These changes move where the flag is checked so that we execute all of the task code other than actually sending the message.  This includes updating DynamoDB.
Per request from QA, these changes set the feature flag to False in Perf.
issue #1747
=> #1747 Moved the location of the Comp & Pen feature flag check

.talismanrc, app/celery/scheduled_tasks.py, app/config.py, cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-beat-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json, tests/app/celery/test_scheduled_tasks.py
These changes add the variable COMP_AND_PEN_SMS_SENDER_ID to the task definitions for all environments and implement its use in the celery task that sends Comp & Pen notifications.  The logic is:
1. When COMP_AND_PEN_SMS_SENDER_ID is a valid UUID, send notifications with the ServiceSmsSender instance associated with that ID.
2. Otherwise, send notifications using the default sender for the service associated with the task definition variable COMP_AND_PEN_SERVICE_ID.
The new variable probably isn't needed in all three definitions for each environment, but including it only in a subset would be inconsistent with all the other variables.  We have #1711 to address this.
In the test file I modified, in addition to adding a new test, I moved all the fixtures to the top of the file.
issue #1749 …
=> #1749 Comp & Pen SMS sender ID

.github/workflows/cd-pipeline.yml
issue #1725 
This is a necessary merge in order to start squashing merges to the release branch so the release notes are not bloated as [they are here](https://github.com/department-of-veterans-affairs/notification-api/releases/tag/untagged-2223a302a7183d3b9460). 
Please see [this deploy to …
=> #1725 - Squash and Merge Release

.github/scripts/actionUtils.js, .github/scripts/createAndPostTag.js, .github/scripts/createReleaseNotes.js, .github/scripts/prData.js, .github/scripts/prLabelSemver.js, .github/scripts/preTagSummary.js, .github/workflows/cd-pipeline.yml, .github/workflows/create-and-post-tag.yml, .github/workflows/create-release-notes.yml
The goal of this PR is to create a draft release and release notes as a part of our pipeline, as well as providing a convenient link for QA to review the draft release notes.  
The release notes are generated with the same file our current release notes are generated from.  They should look [something like this](https://github.com/department-of-veterans-affairs/notification-api/releases/tag/v1.7.9), and should always be generated based off comparing the previous release tag's value with the new release version. 
The javascript files in this PR were formatted according to …
=> #1725 Version Release Notes Generation

.github/workflows/cd-pipeline.yml, Makefile
issue #1726 
This is a simple but important change to our pipeline to finally deploy to production. 
Upon merge of this PR, we will begin using this pipeline for our deployment process. 
This PR has the enhancement label, so it will semver bump a minor version.  This is because the plan is to move from v1.7.12 to 1.8.0.  I tested this transition, as well as the new code, in my POC repo; please see the testing section below. 
In preparation for merging this PR, all non-"v" tags were deleted, tag 1.7.12 was created, and the RELEASE_VERSION repo variable was adjusted to 1.7.12.  
This PR also fixes a bug where deploys …
=> #1726 - Deploy to Prod from CD Pipeline

tests/app/dao/test_users_dao.py
Removed print statement from test that was addressed in a security scan. The information printed was not confidential.
issue N/A
=> HOTFIX - Removed Unnecessary Print In Test

Makefile, cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-beat-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json
issue [#823](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-infra/823)
- Update name of DynamoDB to new name updated in this [infra PR](https://github.com/department-of-veterans-affairs/vanotify-infra/pull/831)
- Test lambda that use DynamoDB …
=> INFRA-823 - Update cache dynamo table value

app/config.py
This change is to give some breathing room for testing the changes being made in #1826 before the prod data ends up going through the pipeline.
> [!Note]
> I did expand the hours in this change so we can see logs earlier in the day, if this is a problem I will put them back.
issue #N/A
- We have done this many times and it works as expected.
=> Delay Comp and Pen Scheduled Messages till Monday - 24th

app/config.py
This PR sets the cron to the agreed upon schedule for sending notifications at the end of each month.
issue #N/A 
- This is just a change to the cron schedule which we do frequently for testing and know that it works.
=> Update Comp and Pen Scheduled Message Cron

.github/pull_request_template.md
This PR adds a link to the PR template for the updated documentation for PR naming.
issue [TEAM-#1326](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1326)
- Documentation changes only
- See the [PR section of the team agreement](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/team_agreement.md#opening-and-reviewing-prs)
=> TEAM-1326 Add Link to PR Template for Naming Documentation

.github/ISSUE_TEMPLATE/notify-dependency-update-template.md
Updated the API dependency issue template to more accurately cover the work needed.
issue - none - hotfix
=> Hotfix - Update Dependency Issue Template

app/googleanalytics/ga4.py
These changes are an addendum to my [previous PR](https://github.com/department-of-veterans-affairs/notification-api/pull/1859) to log validation error messages.  This is to troubleshoot any future issues with GA4 given that nobody will see the GA4 GET route response in real time unless they are a team member actively testing it.
issue #1853
I ran the app locally and made a request that did not include the required "campaign" URL parameter.  The server logs output `ERROR 2024-07-11 14:26:31,617 /app/app/googleanalytics/ga4.py:35: GA4 ValidationError: 'campaign' is a required property`.  QA also identified error logging on Perf.
=> #1853 - Log validation errors

.talismanrc, poetry.lock, pyproject.toml, tests/app/conftest.py, tests/app/letters/test_letter_utils.py, tests/lambda_functions/two_way_sms/test_two_way_sms_v2.py
This PR updates the moto dependency to `~=5.0` and includes the changes necessary for this upgrade.
issue #1624 
=> #1624 Update moto for Test Container

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py, tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
While working with VEText there were messages about retrieving parameters from SSM with every invocation. Investigation found that it was not actually calling SSM every invocation. Logging adjusted. 
Small logic adjustment to the request SSM method as well to be more pythonic. Would have preferred raising an exception but that far exceeded the intended scope. Skipped moving the logging statement out of the try block to avoid unnecessary branching (no need for an else just to log).
On failures we log the entire incoming request in case we need it but the body of an incoming text is more information than we need for diagnosing issues. Redacted the body of the incoming text when logging, but did not change the actual body.
issue N/A
Unit tests still pass. …
=> HOTFIX - Cleaned VEText Forwarder Logging

poetry.lock
- This is a Poetry update for the notification-utils dependency to capture [changes in this PR.](https://github.com/department-of-veterans-affairs/notification-utils/pull/160)  
[issue #159](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-utils/159)
=> UTILS-159 - Update pixel image to have alt text

.talismanrc, poetry.lock
Use the latest notification-utils commit that support markdown for h3 in e-mail templates.
issue [UTILS 154](https://github.com/department-of-veterans-affairs/notification-utils/issues/154)
See notification-utils PR [161](https://github.com/department-of-veterans-affairs/notification-utils/pull/161).
=> UTILS-154 Use the latest notification-utils commit

.pre-commit-config.yaml, lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
Updated retryable errors from `error` to `warning` so we are not looking at these retryable events as errors. Updated pre-commit hooks.
`nosec` and `noqa` were added because pre-commit checks were failing even though the code was unchanged. Bandit doesn't like our method of testing (we're in agreement!) and the method was at a complexity of 13.
Skipping the slides bullet since this is just changing logs from error to warning. Will consider adding it back if the key wins are looking light.
issue N/A
Deployed. All tests pass. This was simply a log level change (error -> warning), with no content being modified. Along with a pre-commit change which has no bearing on running code.
=> HOTFIX - Changed error to warning for retryable failures

cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json
This PR enables `VA_PROFILE_V3_USE_PROFILE_API_V3` for staging and perf environments.  Once testing has completed, we will enable the flag in prod
issue [#1916 ](https://github.com/department-of-veterans-affairs/notification-api/issues/1916)
This functionality has been tested with Postman and regression tests.
=> Enable VA_PROFILE_V3_USE_PROFILE_API_V3 in staging, perf

cd/application-deployment/prod/vaec-celery-task-definition.json
`VA_PROFILE_V3_USE_PROFILE_API_V3` Is enabled in all lower environments and functionality checks out.  Now it's time to enable in prod
issue #[1920](https://github.com/department-of-veterans-affairs/notification-api/issues/1920)
=> #1920 - enable feature flag VA_PROFILE_V3_USE_PROFILE_API_V3 in production

app/attachments/store.py, app/callback/sqs_client.py, app/clients/sms/twilio.py, app/cronitor.py, app/dao/dao_utils.py, app/dao/notifications_dao.py, app/dao/services_dao.py, app/delivery/send_to_providers.py, app/errors.py, app/googleanalytics/ga4.py, app/integrations/comp_and_pen/scheduled_message_helpers.py, app/mobile_app/mobile_app_registry.py, app/notifications/aws_sns_status_callback.py, app/notifications/notifications_govdelivery_callback.py, app/notifications/notifications_ses_callback.py, app/notifications/send_notifications.py, app/notifications/utils.py, app/oauth/rest.py, app/service/whitelist_rest.py, app/status/redis_check.py, app/user/rest.py, app/v2/errors.py, app/va/va_profile/va_profile_client.py, app/va/vetext/client.py, tests/app/mobile_app/test_mobile_app_registry.py, tests/app/notifications/test_send_notifications.py, tests/app/va/vetext/test_client.py
These changes primarily modify logging statements in "except" blocks other than occurrences in files within app/celery/ (which are actually the majority; the ticket specifies not changing them).
- I replaced "error" with "exception".
- For "warning" level logging, I made judgement calls.  A number of the warnings occurred in Flask route error handlers, and I changed those to "exception".
- For "critical" level logging with exception info embedded, I generally kept the critical logging statement but moved the traceback to a separate "exception" logging statement.  This preserves our ability to create alerts for critical events.
- For occurrences of `except Exception as e:` in which "e" is not needed in the associated block, I replaced it with `except:`, which is the syntactically correct …
=> #1874 exception logging

Makefile
issue # N/A - Hotfix
- Update Makefile to ignore dependency vulnerability for Gunicorn 22.0.0 
- Allow test / dependency-scan  Github Workflow to run and confirm passes
=> HOTFIX - Ignore dependency vulnerability Gunicorn 22.0.0

.github/ISSUE_TEMPLATE/notify-dependency-update-template.md, .github/pull_request_template.md, .github/scripts/trigger-regression.js, .github/workflows/build.yml, .github/workflows/cd-pipeline.yml, .github/workflows/deploy-release.yml, .github/workflows/deploy_lambda_dev.yml, .github/workflows/deployment.yml, .github/workflows/dev_deploy.yml, .github/workflows/lambda-functions.yml, .github/workflows/load-test-email-delivery-time.yaml, .github/workflows/load-test-sms-response-time.yaml, .github/workflows/test-github-actions.yml, .github/workflows/tests.yaml, .github/workflows/update-datadog-image.yaml, README.md, app/clients/sms/twilio.py, documents/cds-to-va-changes.md
issue #1905 
We are renaming our default branch `master` to `main`. In this PR, I have updated all references to  notification-api's `master` branch to `main`. 
- Renamed `master` to `main` and deployed branch. 
- Ran Github Actions with Workflow branch as `1905-rename-master-to-main` and deployment branch as `main`
Per @cris-oddball, cannot test until PR is merged into main. 
Per @cris-oddball, cannot test until PR is merged into main. 
Per @cris-oddball request, I will not be testing these. And instead, these will be tested on Perf later. These tests are being rewritten and does not matter if they break.
Per @cris-oddball request, I will not be testing these. And instead, these will be tested on Perf later. These tests are being rewritten and does …
=> #1905 - Rename master to main in Github Workflows and Docs

.talismanrc, poetry.lock, pyproject.toml
This PR updates the notification-utils dependency so we have the bugfix from [utils-127](https://github.com/department-of-veterans-affairs/notification-utils/issues/127) in place.
issue [utils-127](https://github.com/department-of-veterans-affairs/notification-utils/issues/127)
- See [utils PR](https://github.com/department-of-veterans-affairs/notification-utils/pull/171) for details
=> UTILS-127 Bug: Update notification-utils for Email Preview Exposes HTML Tags

.talismanrc, gunicorn_config.py, poetry.lock, pyproject.toml
Removal of eventlet from gunicorn to fix an "RLock" issue.
issue #1963 
Testing has been done over the last few days, culminating in a planned comparison test between the two. The [tests revealed](https://vanotify.ddog-gov.com/notebook/9099/cris-load-test-for-gunicorn-aug-29-2024-09-35) very similar behavior between the two. We are going to proceed with removal of eventlet.
=> #1963 - Remove Eventlet Gunicorn Worker

.github/pull_request_template.md
This updates the Pull Request template:
- remove Type of Change checklist
- clarify when a ticket is moved to Dev testing lane checkbox
- remove checkbox for adding content to sprint demo (will now be in tickets)
issue N/A hotfix, no ticket
- Deployed to Dev
=> Hotfix - Update PR template to remove 'Type of Change' section

app/celery/process_delivery_status_result_tasks.py
Updated the log level to `warning` to be in-line with our policy of [non-standard path](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/logging_policy.md#non-standard-path).
issue N/A
Logging change, but [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/10796056043) anyways.
=> HOTFIX - Updated Log Level and Message For Delivery Status "should_exit"

.github/pull_request_template.md
Updated the PR template to point to the current PR labeling scheme here: https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/pull_request_labels.md#vanotify-labels
issue #1970 
Nothing to test here, just a doc change.
=> #1970 - Update PR template to point to current labeling scheme

.github/release.yaml
Per team consensus, we are getting rid of the top level headers in our release notes. Below is an image of how release notes will look with this change in place.
issue #1970
=> #1970 - Set category for release notes to empty string

.talismanrc, app/celery/contact_information_tasks.py, app/celery/lookup_recipient_communication_permissions_task.py, app/va/va_profile/va_profile_client.py, tests/app/celery/test_contact_information_tasks.py, tests/app/conftest.py, tests/app/va/va_profile/test_va_profile_client.py, tests/app/va/va_profile/test_va_profile_client_for_profile_v3.py
This started as an [UnboundLocalError](https://docs.python.org/3/library/exceptions.html#UnboundLocalError) due to a variable not being set. There were some issues with the logic that needed fixing as well. Cleanup here and there, and some new test cases.
issue N/A
Wrote new unit tests and deployed to dev, perf, and staging with the feature flag on and off. All unit and regression tests pass.
=> HOTFIX - Updated Permission Logic

cd/application-deployment/prod/vaec-celery-task-definition.json
This PR is simply turning on the `VA_PROFILE_EMAIL_STATUS_ENABLED` feature flag in production.
issue #1780 
- This feature is working in all the lower environments and will be verified as working when this is deployed to prod.
=> #1780 - Prod: Configure the send email notification delivery status to VA Profile

.talismanrc, ci/docker-compose-test.yml, lambda_functions/pinpoint_callback/pinpoint_callback_lambda.py, tests/lambda_functions/pinpoint_callback/test_pinpoint_callback_lambda.py
The sqs resource was being defined in the lambda's handler function and therefore was reinstantiated every time the lambda would run. This moved the sqs resource to the execution environment so the lambda will run more efficiently when it's not running from a cold start.
issue #1466 
This doesn't change any logic, just moves the sqs resource initialization outside of the lambda handler.
=> #1466 - Pinpoint Lambda Speedup

app/va/va_profile/exceptions.py, app/va/va_profile/va_profile_client.py, tests/app/va/va_profile/test_va_profile_client_for_profile_v3.py
In cases when we have determined that a telephone number cannot receive SMS messages, return a Non-retryable exception with the reason: "Phone number is invalid"
Issue #2009 
VA IIR issue [1103](https://github.com/department-of-veterans-affairs/va-iir/issues/1103)
=> #2009 - Raise InvalidPhoneNumberException on invalid (landline, etc) telephones

cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json
This PR enables the VA Profile V3 flags in all environments. Once this looks good on Prod IIR can proceed with removing these feature flags.
issue N/A
- This is already deployed and tested on Dev and Perf, so we will just be looking for problems as it goes up to Prod.
=> HOTFIX - Enable VA Profile v3 Flags

documents/openapi/openapi.yaml, documents/postman/README.md, documents/postman/internal_api_developers/notification-api.postman_collection.json, documents/postman/notification-api-simplified.postman_collection.json
As part of the VA's Zero Silent Failure Initiative (see [epic](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1391)), we are updating the OpenAPI spec and Postman collections to add in a new property, `callback_url`,  to POST `v2/notifications/<email | sms>` payloads and the GET `v2/notifications/:notification_id `response, so that our clients can be aware of this property.
- Updates the simplified Postman collection for the POST `v2/notifications/<email | sms>` routes.
- Updates the Internal Developer Postman collection  for the POST `v2/notifications/<email | sms>` routes.
- Adds path descriptions to the Swagger POST `v2/notifications/<email | sms>` for additional information on all properties.
- Updates the …
=> #2000 - Update Postman and Swagger to include the new callback url

.github/workflows/dev-tests.yml
We have failing tests due to our Github Actions Runners using Ubuntu 24, which is caused by the usage of the `ubuntu-latest` label in our workflow. We want to pin that to v22 so that our tests can pass and unblock ourselves from work.
Successful previous run:
Failed new run:
We will make sure CI works once this PR is opened. That will determine that this was "tested" correctly. Will also check the workflow to make sure Ubuntu 22 is being run.
=> HOTFIX - Use ubuntu 22 for dev tests

migrations/versions/0371_replace_template_content.py, migrations/versions/0371_replace_template_history_content.py
- Removing Canada-related URLs in the Template or TemplateHistory content
- **Note** - This change is not reversible and has been confirm with Product. 
issue #805 
[Deployed to Dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11261201841)
[Ran Downgrade - Did not revert changes and no errors](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11261408500)
**Note** `{{notification-api-url}}/service/{{service-id}}/template/{{template-id}}/version/1` uses TemplateHistory model. Used to route to test the update to TemplateHistory content attribute
**Template**
**Template History**
**Template**
**Template History** 
**Template**
**Template History**
- [n/a] I have commented my code, particularly in hard-to-understand areas
- …
=> #805 - Correct Canada Url in Template History

.talismanrc, poetry.lock, pyproject.toml
issue #1886 
- Unpinning protobuf! 
- Ran `poetry update`
[Deploy is A-OK!](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11294533482)
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to any documentation
- [n/a I have added tests that prove my fix is effective or that my feature works. [Testing guidelines](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Process/testing_guide.md)
- [n/a] New and existing unit tests pass locally with my changes
=> #1886 - Update protobuf

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
One line log addition to help with 502 error tracking.
=> HOTFIX - Added MessageSid Being Processed in Forwarder

.talismanrc, README.md, app/__init__.py, app/callback/webhook_callback_strategy.py, app/celery/process_ga4_measurement_tasks.py, app/celery/process_ses_receipts_tasks.py, app/celery/service_callback_tasks.py, app/clients/email/govdelivery_client.py, app/clients/performance_platform/performance_platform_client.py, app/cronitor.py, app/notifications/utils.py, app/notifications/validators.py, app/template/rest.py, app/user/rest.py, app/va/mpi/mpi.py, app/va/va_onsite/va_onsite_client.py, app/va/va_profile/va_profile_client.py, migrations/versions/0372_remove_service_id_index.py
Removed index after consulting a data engineer.
Used read instance for GA4 lookups.
Cached sms sender id lookups.
Changed lower env timeouts to 30 seconds for the connection and 30 seconds between bytes (read).
issue #2069 
GA4 update to use DB read instance:
Caching: Reduced service sms sender id lookups (only made 4 queries for that method, one for each worker):
Regression suite passed all tests other than two expected failures due to VA Profile users being changed. More specifically it appears communication permissions in the dev environment is broken for them.
=> #2069 - Reduced Write Instance Queries

app/config.py
The payments team is having a problem, so we are delaying the Comp and Pen notifications until the 24th hoping the issue will be resolved by then.
issue N/A
- This is just changing the cron of the Comp and Pen notifications, which we have done several times
=> HOTFIX - Push Back Comp and Pen Notifications

.talismanrc, lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py, tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
We recently had a series of warnings due to incoming messages from Twilio that did not contain a body. They didn't have a body because the message type did not have one. We merely forward those messages but the group we forward to was not able to handle the missing `Body` field. 
Redacted sensitive information, added a log statement, and abort that particular record.
issue N/A
New unit test made. Built a new custom message just for this case where the Twilio "Body" field does not exist. Existing tests pass. Deployed.
=> HOTFIX - Added Log Statement For Expected Missing Twilio Body

cd/application-deployment/dev/vaec-api-task-definition.json, ci/Dockerfile
This PR adds a health check to the ECS task definition, so ECS can better manage those tasks/services.
issue #1966 
I [deployed this to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11522691653) and observed the health message in the ECS console  -
=> #1966 ECS health check for API

.github/ISSUE_TEMPLATE/bug-report-template.md, .github/ISSUE_TEMPLATE/hotfix-template.md
In order to track hotfix efforts, a hotfix template is created. Additionally, the bug template now include the bug label.
issue None
- Cannot be fully tested until deployed, but reviewed the markdown preview to my satisfaction
- [Regression passed](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/11634803622) (this change wouldn't affect the running app, though)
- Unit tests passed (this change wouldn't affect the running app, though)
=> HOTFIX - create hotfix template

.github/workflows/cd-pipeline.yml
This PR automates the posting of release notes to Oddball's Slack workspace.
issue #1972 
Tested posting to Slack here:
=> #1972 - Automate release note posting to Oddball Slack

.github/ISSUE_TEMPLATE/notify-dependency-update-template.md, .github/workflows/dependency-ticket-creation.yml
This PR implements a cron based Github Action Workflow that creates a Dependency update ticket based on our template every 2 weeks. It created a ticket while I was testing, and is currently set to run again the weeks in between planning.
The way that Github Actions evaluates crons made it impossible to start the cron on the Mondays that we have planning. I would have had to implement this next week in order for it to evaluate correctly. IMO, this is fine.
issue #1381 
Ticket created by workflow:
https://github.com/department-of-veterans-affairs/notification-api/issues/2103
With issue already existing, the following was printed:
=> #1381 - Implement workflow to automatically create dependency update tickets

app/config.py
Reset the cron for Comp and Pen notifications back to the 22nd of the month. Last month the payments team had and issue, so we had to adjust the date back. Now we must put it back to where we previously had it.
issue N/A
- This simply resets the cron for Comp and Pen notification to start on the 22nd, since we had to adjust it last month.
=> HOTFIX - Reset Comp & Pen Notification to start on day 22

documents/openapi/openapi.yaml, documents/postman/internal_api_developers/notification-api.postman_collection.json, documents/postman/notification-api-simplified.postman_collection.json
Saw us sending to example.com/callbacks. Didn't think about it at the time but we should be directing them to a va.gov resource as an example.
issue #2133
=> #2133 - HOTFIX to Update Postman and Swagger

app/clients/sms/twilio.py, tests/app/clients/test_twilio.py
This PR adds exception handling for Twilio messages exceeding the 1600 character limit by catching that code and raising a non-retryable exception.
issue #2070
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/12165822563)
- Sent a message, longer than 1600 characters and observed no retries in [Datadog](https://vanotify.ddog-gov.com/logs?query=host%3Adev-notification-api-log-group%20%22a874dd75-5709-4b2b-b2a0-3fd8a3f189db%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=expanded-lg&refresh_mode=paused&storage=online_archives&stream_sort=service%2Casc&viz=stream&from_ts=1733335142063&to_ts=1733337788000&live=false)
=> #2070 Retrying Twilio 400 Errors

app/va/va_profile/va_profile_client.py
issue #2137 
Update logging statement to capture notification status
- Called `v2/notification/sms` with invalid phone and [checked logs](https://vanotify.ddog-gov.com/logs?query=host%3Adev-notification-api-log-group%20%22e7c41d7a-0310-496d-9ede-51b860c9a6c2%22%20%22VA%20Profile%20response%20when%20receiving%20status%20of%20notification_id%3A%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1733429406961&to_ts=1733430306961&live=true)
=> #2137 - Update logging statements to capture notification status

.talismanrc, app/celery/tasks.py, app/models.py, poetry.lock, pyproject.toml, tests/app/dao/test_fact_notification_status_dao.py, tests/app/delivery/test_send_to_providers.py
This is a companion PR for a Utils PR to upgrade Mistune to v3.0.2.
- Update the Poetry files to use the newest Utils
- Rename template.placeholders to template.placeholder_names to reflect changes made in Utils
- Remove references in the tests to GOV.UK and letter templates, which no longer exist.
issue [UTILS-169](https://github.com/department-of-veterans-affairs/notification-utils/issues/169)
QA and I deployed this branch and tested it before merging the Utils branch.  We verified that notifications sent with the code on this branch remain unchanged compared to notifications sent with the code in production.  See the [Utils PR](https://github.com/department-of-veterans-affairs/notification-utils/pull/187) for screenshots.
=> UTILS-169 Upgrade Mistune to v3

app/config.py
Updating to run on a non-weekend.
issue N/A
N/A
=> HOTFIX - Update Comp and Pen Cron due to Holidays

app/commands.py, app/dao/date_util.py, app/utils.py, migrations/versions/0183_alter_primary_key.py
These changes replace all instances of the timezone `America/Toronto` with `America/New_York`.
issue #1350
All unit tests continue to pass, and `grep -rni Toronto` no longer returns any hits.
=> #1350 Use America/New_York time zone by default

.github/workflows/task-defnition-cleanup.yaml
This PR introduces a GHA workflow that echos "hello world". I need this GHA in main so that I can use workflow_dispatch to begin testing task definition cleanups.
issue TEAM 1177
Nothing to test here. It's an empty GHA workflow.
=> TEAM #1177 - Add empty GHA workflow to begin testing task definition cleanup

documents/openapi/openapi.yaml
Update Swagger to reflect the notification statuses as revised for #2163.
issue #2035
I manually inspected using the [Swagger Editor](https://editor-next.swagger.io/).
=> #2035 Update Swagger to reflect the notification statuses as revised

lambda_functions/va_profile/va_profile_opt_in_out_lambda.py, scripts/run_tests.sh, tests/lambda_functions/va_profile/test_va_profile_integration.py
VA Profile changed nonprod certs. We need to make sure there is no downtime between when the new and old certs are swapped. This code change allows both to exist at the same time.
issue N/A
Deployed to staging and used test users to toggle the flag for comp & pen. 
[Deployed through GHA](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/12589345467) to dev.
=> HOTFIX - Update opt in/out Lambda to Handle Multiple Certs

pyproject.toml, scripts/run_tests.sh
We have seen mistakes with Poetry versions a few times. This PR fixes that issue by enforcing a version in pyproject.toml that is checked in `run_tests.sh`
issue N/A
Deployed [check](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/12603680193/job/35129171920?pr=2223#step:6:28).
Running the script locally:
Running it in docker:
=> HOTFIX - Enforce Poetry Version

app/service/service_callback_api_schema.py, tests/app/service/test_schema.py
Remove the update_service_inbound_api_schema and associated tests.  This schema is not used.
issue #1748
=> #1748 Remove the update_service_inbound_api_schema and associated tests.

app/celery/provider_tasks.py
The referenced issue turned out to be unnecessary.  This is a quick PR to comment a part of the code that caused confusion while investigating the ticket.
issue #2222
=> #2222 Added comments about rate limiting.

.github/workflows/cd-pipeline.yml
This PR adds a step to the end of the CD pipeline that posts the link to the release notes to the VA Slack workspace (in our public VA channel).
issue #2106 
The actual message and the formatting was tested when we initially implemented this for Oddball Slack (https://github.com/department-of-veterans-affairs/notification-api/pull/2098), so I opted to not retest this. To view how this was originally tested, along with the format of the message, click the linked PR above.
=> #2106 - Add release notes to VA Slack in CD pipeline

.github/actions/build-push-artifacts/action.yml
This PR disables the Twistlock workflow. It does this by commenting out the part of the build action where it gets called. For context into why this is being done, refer to the hotfix ticket below.
issue #2252 
N/A
=> HOTFIX - Disables the dispatching of Twistlock workflow

lambda_functions/two_way_sms/two_way_sms_v2.py
Cleaning up logging! This is sent to SQS for retry, thus a warning log should be used.
issue N/A
N/A. Change of warning type without changing the content does not warrant testing.
=> HOTFIX - Updated Retryable Error Log to Warning

.talismanrc, app/schema_validation/__init__.py, tests/app/test_validate.py
This PR adds exception handling to the schema validation method. The `validate` method now enforces that all payloads be a python dictionary.
issue #888 
- old and new unit tests pass
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/12837778967), regression tests pass
=> #888 Prevent AttributeError in json validation

ci/Dockerfile
This PR updates pip and setuptools for the alpine image running our code. These versions of pip and setuptools are not actually used by our code, since we use the versions in the virtual env.
issue [team #1446](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1446)
=> TEAM-1446 Update Dependencies in Dockerfile

.talismanrc, poetry.lock, pyproject.toml
These changes encompass an update of notification-utils.
issue [UTILS 181](https://github.com/department-of-veterans-affairs/notification-utils/issues/181)
Please see the [UTILS PR](https://github.com/department-of-veterans-affairs/notification-utils/pull/194) for evidence of proper function.
=> UTILS-181 Lists in block quotes

cd/application-deployment/dev/vaec-api-task-definition.json, cd/application-deployment/dev/vaec-celery-beat-task-definition.json, cd/application-deployment/dev/vaec-celery-task-definition.json, cd/application-deployment/perf/vaec-api-task-definition.json, cd/application-deployment/perf/vaec-celery-beat-task-definition.json, cd/application-deployment/perf/vaec-celery-task-definition.json, cd/application-deployment/prod/vaec-api-task-definition.json, cd/application-deployment/prod/vaec-celery-beat-task-definition.json, cd/application-deployment/prod/vaec-celery-task-definition.json, cd/application-deployment/staging/vaec-api-task-definition.json, cd/application-deployment/staging/vaec-celery-beat-task-definition.json, cd/application-deployment/staging/vaec-celery-task-definition.json
This PR updates the datadog agent container to the latest version (at the time of writing, 7.62.1).
issue #2250 
Successful image build/push: https://github.com/department-of-veterans-affairs/notification-api/actions/runs/13158679118
New version in dev:
APM still functional:
=> Upgrade datadog agent to 7.62.1

.github/workflows/cd-pipeline.yml
=> #9999 - Testing Release Notes

.talismanrc, poetry.lock, pyproject.toml
Use notification-utils v2.3.3, which upgrades  the Python "phonenumbers" package.
issue [UTILS 143](https://github.com/department-of-veterans-affairs/notification-utils/issues/143)
Unit and regression tests pass.
=> UTILS-143 Upgrade phonenumbers

.talismanrc, app/models.py, migrations/versions/0375_add_key_revoked.py, tests/app/dao/test_api_key_dao.py, tests/app/db.py
Updating API keys to include an `expiry_date` requires adding a `revoked` property to the `api_keys` table to track revoked keys during the transition. This change will take time due to required coordination with service users. Additionally, the unique constraint on active key names per service has been removed, as the names are rarely used, and adjusting the constraint would have required multiple PRs and manual database changes.
issue #2260
=> #2260 - Add Revoked Field to api_keys Table

app/clients/sms/aws_pinpoint.py, app/clients/sms/twilio.py, app/delivery/send_to_providers.py, app/v2/notifications/post_notifications.py, tests/app/delivery/test_send_to_providers.py
Log just prior to requesting the provider send the message. Captured the time when we first accepted the request and set the created_at time to that so we could track how long to actually send it.
issue #2169 
Deployed. New logs are there.
=> #2169 - Log Total Time To Send

.talismanrc, poetry.lock, pyproject.toml
Upgrade notification-utils to v2.4.0 (latest).  This incorporates changes to permit elements h4-h6 in markdown.
issue [Utils 201](https://github.com/department-of-veterans-affairs/notification-utils/issues/201)
Please see [Utils PR 217](https://github.com/department-of-veterans-affairs/notification-utils/pull/217) for details.
=> UTILS-201 Add headers 4-6 for Portal

.talismanrc, documents/openapi/openapi.yaml, documents/postman/internal_api_developers/notification-api.postman_collection.json
Added `include_revoked` to the Postman collection.
issue #2311
- Deleted my notification-api collection, re-imported and tested.
=> #2311 - Postman update for api keys

.gitignore, tests/app/service/test_sender.py
Some tests were using the VA Notify service when sending notifications to all users of a service. That IS our expected behavior but the tests were hitting race conditions. Used a "sender" service that mocked the Notify service to remove all race condition possibilities.
Only unit tests were modified.
issue N/A
Tested locally. All tests in the file pass. GHA Unit tests pass. Deployed.
=> HOTFIX - Removed session-based Tests

app/celery/process_ses_receipts_tasks.py
=> HOTFIX - Ensured status_reason was Bounce

.talismanrc, poetry.lock, pyproject.toml, tests/app/notifications/test_process_notifications.py
issue HOT FIX
- Update alembic package which is a sub-dependency of top level package alembic-utils. [Alembic 1.15.0 yanked. Must use 1.15.1](https://alembic.sqlalchemy.org/en/latest/changelog.html)
- Add setuptools as top level dependency and pin as `77.0.3` to [fix issue with most recent version](https://github.com/pypa/setuptools/issues/4910)
- Mark flakey tests as `serial`
- Confirm tests run 
- [Deploy to dev OK](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/14045440146)
=> HOT FIX - Update Alembic and Setuptools

app/celery/process_ses_receipts_tasks.py, app/celery/provider_tasks.py, app/delivery/send_to_providers.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/celery/test_provider_tasks.py, tests/app/delivery/test_send_to_providers.py
Small refactor to only check status_reason for bounces. Also ensures that if there is a duplicate attempt to send a notification we simply log a warning and then raise a technical failure for the Celery task (so we can look into it). We do not want to do anything to the notification in that case.
Added several comments.
issue #2366 
Wrote new test cases to cover this. Tests pass locally, pass in the GHA. Deployed (soon).
=> #2366 - Ensure No Duplicate Emails

app/notifications/validators.py
Unfortunately, changing the "message" as suggested in the ticket would be a breaking change to our clients. Added an extra log statement with more data.
issue #2375 
This is just an extra log statement. Deployed and tested it on perf since Dev was being used. Log statement can be viewed here:
=> #2375 - Better Validation Failure Logging

.github/workflows/dev-tests.yml
This PR removes the docker-compose down command from the test suite to remove duplicate messages from our GHA output logs.
Before change:
After change:
The docker network hanging around is fine... the repo is public, as are the compose files, and the GHA runners are ephemeral.
=> HOTFIX - Remove docker-compose down from test suite

app/delivery/send_to_providers.py, app/inbound_number/rest.py, app/notifications/process_notifications.py, scripts/run_tests.sh, tests/app/billing/test_billing.py, tests/app/clients/test_aws_ses.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py, tests/app/dao/notification_dao/test_notification_dao_performance_platform.py, tests/app/dao/test_ft_billing_dao.py, tests/app/dao/test_provider_details_dao.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_templates_dao.py, tests/app/dao/test_users_dao.py, tests/app/delivery/test_send_to_providers.py, tests/app/inbound_number/test_rest.py, tests/app/notifications/test_process_notifications.py, tests/app/platform_stats/test_rest.py, tests/app/provider_details/test_rest.py, tests/app/service/test_callback_rest.py, tests/app/service/test_rest.py, tests/app/status/test_status.py, tests/app/v2/notifications/test_get_notifications.py, tests/lambda_functions/conftest.py, tests/lambda_functions/pinpoint_callback/test_pinpoint_callback_lambda.py, tests/lambda_functions/va_profile/test_va_profile_integration.py
Went through the remainder of these tests. 
- Added some comments and updated minor logging for the 3 app files touched. 
- ~Updated the test script to use [worksteal](https://pytest-xdist.readthedocs.io/en/stable/distribution.html)~ Our tests are too brittle. They were designed to be dependent on each other and there's no way to use worksteal without significant overhaul.
- Removed all `@pytest.mark.serial` that were possible with a little effort.
- Commented many of the remaining serial tests. Added `# Cannot be ran in parallel` and a description if applicable/known
Test run time didn't change too much.
issue #2362 
Extensive local testing. Tested with the PR then ran it again to make sure there wasn't any test shifting that would cause this to fail for others. Made another minor change …
=> #2362 - Make Serial Tests Parallel pt2

app/celery/process_delivery_status_result_tasks.py
This is just to update the logs for SMS updates to include the service and template IDs. This will help us to track client issues as well as allow us to see what template issues at a log level in addition to DB/BQ.
issue N/A
Deployed, working for Twilio and Pinpoint:
=> HOTFIX - SMS Log Update

.github/workflows/dev-tests.yml
This PR modifies the unit test GHA workflow to pgdump and upload the notification API schema to S3. This will then be used by ENP to run unit tests.
issue #2389 
CI/tests passed and the sql schema lives in the S3 bucket.
=> #2389 - Add schema dump and upload command for database

.github/workflows/dev-tests.yml, Makefile, README.md
safety has been deprecated for a while. They moved to a paid model and we hadn't cut it out. We have other, more detailed methods of scanning now.
issue N/A
=> HOTFIX - Removed safety

.talismanrc, poetry.lock, pyproject.toml
Upgrade notification-utils to v2.5.2 (latest). This incorporates changes to escape URL whitespace in markdown links and images.
issue [UTILS-188](https://github.com/department-of-veterans-affairs/notification-utils/issues/188)
https://github.com/department-of-veterans-affairs/notification-utils/releases/tag/2.5.2
Please see [UTILS PR-235](https://github.com/department-of-veterans-affairs/notification-utils/pull/235)
Validated against local unit tests after UTILS merge, matches GHA unit test results
Deployed to DEV (using UTILS main branch)
- Regressions passed
- Test email success
=> UTILS-188 Escape spaces in Markdown URL's to prevent breaking Markdown processing

app/va/va_profile/va_profile_client.py
VA Profile was seeing 2.5 seconds on the upper-bound for response times to the contact information endpoint. We had a read timeout of 1 second. This PR adjusts things so there is a 3.05 second connection timeout and a 3.05 second read timeout. 
issue N/A
[Deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/14622550856) to dev, regressions pass.
=> HOTFIX - Update VA Profile Timeout

.github/workflows/dev-tests.yml
This PR removes the `-s` flag from the DB schema dump, which only exported the schema. We need the data exported to S3 as well for ENP testing.
@k-macmillan confirmed that the uploaded file to S3 was correct and ran tests against it in ENP. ✅
=> HOTFIX - Remove schema only flag from pgdump

app/inbound_number/rest.py, tests/app/conftest.py, tests/app/inbound_number/test_rest.py
The InboundNumber model has a unique field "number".  These changes catch the IntegrityError that gets raised upon a request that would create or update an InboundNumber instance with the same number.  Not catching the exception resulted in a 500 response.  These errors should now return a 400 response with an appropriate error message.
I also overhauled the unit tests for updating InboundNumbers.  As previously written, they did not adequately test the feature.
issue #1574
This is a straight-forward bug that is easily handled with unit testing.
=> #1574 Inbound number must be unique

app/callback/queue_callback_strategy.py, app/callback/webhook_callback_strategy.py, app/celery/service_callback_tasks.py, app/commands.py, app/dao/service_callback_api_dao.py, app/dao/service_callback_dao.py, app/models.py, tests/app/callback/test_webhook_callback_strategy.py, tests/app/celery/test_nightly_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/celery/test_service_callback_tasks.py, tests/app/dao/test_service_callback_api_dao.py, tests/app/db.py, tests/app/inbound_number/test_rest.py, tests/app/service/test_callback_rest.py, tests/app/test_model.py
These changes [memoize](https://en.wikipedia.org/wiki/Memoization) a database query that retrieves service callback information to reduce the number of database queries.
I also made some changes to the InboundNumber tests to remove hard-coded values and mocking after experiencing intermittent test failures.  I recently worked with InboundNumber code for #1574 but didn't see the problem them.  I think I was just lucky before.
These changes also remove unnecessary mocking in tests that failed after I made changes.
issue #2247
This image depicts queries resulting from sending 20 e-mails using the hammer script.  Note that there aren't 20 queries; just 1 per worker, as prescribed.
=> #2247 cache service callback

.github/workflows/dev_deploy.yml
This PR scopes down the permissions for the dev_deploy.yml workflow. It only allows it `actions: write`, since it needs to kick off other workflows.
TEAM-1633
Ran the dev_deploy.yml workflow (deployed to perf) successfully: https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15169533738
=> TEAM-1633 -- Scope down dev deploy workflow permissions

app/constants.py
Read timeouts were set to 1 second because we could not afford Celery workers waiting around too long. We have since modified the way we use workers and they can sit idle for extended periods of time. Adjusted the read timeout to be more forgiving. 
issue N/A
[Deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15173219369), regression passed.
=> HOTFIX - Update Read Timeout Constant

app/va/va_profile/va_profile_client.py
This PR simply updates the VA Profile read timeout to 7 seconds.
issue N/A
=> HOTFIX - Update VA Profile Read Timeout

app/dao/templates_dao.py, app/models.py, app/notifications/process_notifications.py, app/notifications/send_notifications.py, app/template/rest.py, app/v2/notifications/post_notifications.py, migrations/versions/0379_remove_onsite.py, tests/app/db.py, tests/app/notifications/test_send_notifications.py
These changes remove unused code for onsite notifications.
issue #2415 
I deployed the branch and ran all unit and regression tests.  The [db downgrade works](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15537547554).
=> #2415 Remove onsite notifications code

.github/workflows/cd-pipeline.yml, .github/workflows/db-downgrade.yml, .github/workflows/dependency-ticket-creation.yml, .github/workflows/deploy_lambda_dev.yml, .github/workflows/deployment.yml, .github/workflows/dev-tests.yml, .github/workflows/dev_deploy.yml, .github/workflows/lambda-functions.yml, .github/workflows/load-test-email-delivery-time.yaml, .github/workflows/load-test-sms-response-time.yaml, .github/workflows/run-regression.yml, .github/workflows/tests.yaml
This PR adds GHA permissions to our remaining workflows. The vast majority of our workflows only require read access on repository contents. A few needed write (because our CI/CD pipeline creates tags and releases) and only one needed write access to issues (our dependency update ticket workflow).
team-1633
Deploy to dev worked. We can test the CD pipeline on merge to main. Otherwise, we can just rely on certain workflows throwing errors if they need more permissions.
=> TEAM-1633 - Adds GHA permissions to remaining workflows

.github/workflows/deploy-release.yml
This is the final set of permissions needed for API workflows.
TEAM-1633
The deploy-release workflow was run here: https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15780414686
The workflow failed on finding the correct image in ECR, which is fine. It was still successful in kicking off the workflow.
=> TEAM-1633 -- Add permissions to deploy-release workflow

.github/scripts/trigger-regression.js, .github/workflows/deployment.yml, .github/workflows/run-regression.yml
This PR instruments smoke testing after migrations. For lower environments, smoke the regression will be kicked off after migrations passing `smoke == true`. In prod, `smoke == false`, which means `prodsmoke` will run after migrations.
[issue qa-272](https://github.com/department-of-veterans-affairs/notification-api-qa/issues/272#issue-3136724634)
Two deploys were done to dev to test this change.
**First Test** (mimic lower env deploy, smoke == true)
https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15904107892 is the first deploy, making sure that the `smoke` flag gets correctly passed all the way down to the regression suite. https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/15904203484/job/44854564871#step:7:56 shows that …
=> QA-272 -- Implement smoke test logic after migrations

.talismanrc, app/dao/provider_details_dao.py, app/delivery/send_to_providers.py, app/schema_validation/__init__.py, app/status/healthcheck.py, tests/app/celery/test_ftp_update_tasks.py, tests/app/dao/test_provider_details_dao.py, tests/app/delivery/test_send_to_providers.py, tests/app/test_model.py, tests/app/test_validate.py
This PR removes potentially sensitive information from being logged. The work was done in the file `app/schema_validation/__init__.py`, but there are other file changes made because they were flagged with a `ruff check` command and primarily consist of unused imports.
issue #2527
Example logs
```
Validation failed for: {'template_id': 'fake-template-id', 'email_address': '<redacted>', 'personalisation': {'test': '<redacted>', 'message': '<redacted>'}}
Validation failed for: {'template_id': 'fake-template-id', 'phone_number': '<redacted>', 'personalisation': {'test': '<redacted>'}}
```
=> #2527 - Remove PII from logs

app/callback/webhook_callback_strategy.py, app/celery/process_delivery_status_result_tasks.py, app/celery/process_pinpoint_receipt_tasks.py, app/celery/send_va_profile_notification_status_tasks.py, app/celery/service_callback_tasks.py, app/constants.py
There was an issue that caused retries to repeat excessively last night when we received a 500 error from a service's callback endpoint. This is to remedy that issue by reducing the celery retry backoff to live withing the 5 min visibility timeout of our SQS queues.
issue N/A
=> HOTFIX - Adjust Celery Backoff Time

.github/actions/build-push-artifacts/action.yml, .github/workflows/cd-pipeline.yml, .github/workflows/db-downgrade.yml, .github/workflows/deploy-release.yml, .github/workflows/deployment.yml, .github/workflows/dev-tests.yml, .github/workflows/dev_deploy.yml, .github/workflows/lambda-functions.yml, .github/workflows/load-test-email-delivery-time.yaml, .github/workflows/load-test-sms-response-time.yaml, .github/workflows/task-defnition-cleanup.yaml, .github/workflows/tests.yaml, .github/workflows/update-datadog-image.yaml
This PR implements the OIDC role assumption code to our GHA workflows. It also removes all references to AWS access and secret keys. This can only be merged after https://github.com/department-of-veterans-affairs/vanotify-infra/pull/1083 is merged AND deployed.
issue #2568
https://github.com/department-of-veterans-affairs/notification-api/actions/runs/17242564663 is a deploy using the OIDC role.
=> #2568 - Implement OIDC to AWS in our Github Actions

.talismanrc, app/celery/lookup_va_profile_id_task.py, app/va/mpi/mpi.py, app/va/va_profile/va_profile_client.py, tests/app/celery/test_lookup_va_profile_id_task.py, tests/app/va/mpi/test_mpi_client.py
These changes continue the implementation of the PII_ENABLED flag.  I did most of the required work already for #2538 and #2540.  These changes just shift where a value is encrypted and update tests.
I also fixed a KeyError that showed up in regression testing.  The offending code was merged 11 months ago, and I'm not sure why it failed now.
issue #2539
Unit and regression tests pass.
=> #2539 MPI client PII
