app/clients/email/govdelivery_client.py
tests/app/clients/test_govdelivery_client.py

Granicus will automatically extract plaintext version from html and send a mime/multipart message.
#88

Use html_body when sending emails via Granicus.

---

ci/Dockerfile
ci/Dockerfile.test
ci/Dockerfile.userflow

The scope of changes has narrowed since I opened the underlying issue because it turns out the existing Dockerfiles do delete some of their build dependencies.  The syntax . . .
`apk add --no-cache --virtual .build-deps musl-dev rust cargo git`
. . . creates a "virtual package" named ".build-deps" that includes the packages musl-dev, rust, cargo, and git.  The subsequent delete instruction, `apk del --no-cache .build-deps`, deleted this virtual package, which deletes all the member packages.
I haven't modified Dockerfile.local for this issue because I made the relevant changes for #601.  (They are outstanding in PR 608.)
I tested as follows:
1. Ensured I can build Dockerfile and Dockerfile.userflow.
2. Ran all unit tests.  This also verifies that Dockerfile.test builds.

Reduce Docker images sizes by uninstalling build dependencies

---

ci/Dockerfile
ci/Dockerfile.test
ci/Dockerfile.userflow

I had a syntax error in Dockerfile.  I verified by running `docker inspect` on the image and by running the docker-compose for production.  This clears the PORT error and yields a lot of expected Twillio errors.

Reduce Docker images sizes by uninstalling build dependencies (revision 1)

---

app/models.py
migrations/versions/0345_alter_VAProfileLocalCache.py

This is a straight-forward schema alteration for #632.  When I attempted to create the associated migration using the method described in the README, I encountered this error:
```
db_1          | 2022-04-20 18:34:42.026 UTC [74] ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
db_1          | 2022-04-20 18:34:42.026 UTC [74] DETAIL:  Key (typname, typnamespace)=(alembic_version, 2200) already exists.
db_1          | 2022-04-20 18:34:42.026 UTC [74] STATEMENT:  
db_1          | 	CREATE TABLE alembic_version (
db_1          | 		version_num VARCHAR(32) NOT NULL, 
db_1          | 		CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
db_1          | 	)
```
Eventually, I worked around the error by manually creating the migration script.  Upgrading alembic …

Altered the VAProfileLocalCache class

---

README.md
requirements-app.txt
requirements.txt

#644
This is required in the AWS environment.
https://github.com/benoitc/gunicorn/blob/cf55d2cec277f220ebd605989ce78ad1bb553c46/docs/source/install.rst#async-workers
I rebuilt the Docker images to test this change and picked up multiple package upgrades released within the last 24 hours!

Include the 'eventlet' extras with Gunicorn

---

requirements-app.txt
requirements.txt

With this change, the requirements for Gunicorn and eventlet are in the last known working configuration.  Anything newer causes runtime errors in AWS.  #644

Pinned eventlet to version 0.30.2

---

app/oauth/jwt_manager.py
app/oauth/rest.py
tests/app/authentication/test_authentication.py

There is a login issue for users who has been involved over 20 services because permissions data increase the size of jwt tokens. 
So I took out the `permissions` in jwt token to prevent overflowing and add permissions data in `/my-services/{user-id}` endpoint which has been created [before](https://github.com/department-of-veterans-affairs/notification-api/pull/619).

Remove permissions on JWT token and add it in separate endpoint

---

app/template/rest.py
tests/app/template/test_rest.py

* Create new endpoint in notification-api to preview unsaved template content that admin auth can access.
* Create tests for new route
Related Ticket: https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/department-of-veterans-affairs/vanotify-team/371

Va notify 371/generate template preview admin

---

cd/application-deployment/dev/vaec-api-task-definition.json
cd/application-deployment/dev/vaec-celery-beat-task-definition.json
cd/application-deployment/dev/vaec-celery-task-definition.json
cd/application-deployment/perf/vaec-api-task-definition.json
cd/application-deployment/perf/vaec-celery-beat-task-definition.json
cd/application-deployment/perf/vaec-celery-task-definition.json
cd/application-deployment/prod/vaec-api-task-definition.json
cd/application-deployment/prod/vaec-celery-beat-task-definition.json
cd/application-deployment/prod/vaec-celery-task-definition.json
cd/application-deployment/staging/vaec-api-task-definition.json
cd/application-deployment/staging/vaec-celery-beat-task-definition.json
cd/application-deployment/staging/vaec-celery-task-definition.json

[vanotify-infra#356](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/356)
This PR updates the Fargate container task definitions for datadog-agents to point to the new datadog-gov intstance.

356 datadog agent migration

---

lambda_functions/va_profile_remove_old_opt_outs/requirements-lambda.txt

#681 
Lambda functions in Python that import modules that are not part of the standard library must declare requirements for the AWS Lambda execution environment.  We missed this when reviewing [the ticket's merged PR](https://github.com/department-of-veterans-affairs/notification-api/pull/732).

Additing a requirements file for the va_profile_remove_old_opt_outs lambda

---

.github/workflows/lambda-functions.yaml

The deploy method was statically deploying to both dev and staging on every deployment no matter what environment was entered in during workflow run.  This code changes that to match the environment name passed in.

updated script to dynamically pull env name to deploy to

---

lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
tests/lambda_functions/va_profile/test_va_profile_integration.py

#704
Per our conversation with VA Profile, the Notify team expects that POST requests from Profile will contain JSON with a "bios" attribute that is an array with a single element. This is a consequence of Profile filtering the "bios" before they make their POST request such that communicationItemId is 5 (see #684) and communicationChannelId is not 1 (sms). By process of elimination, communicationChannelId must be 2 (e-mail). For a given veteran, this combination should be unique, and one POST request corresponds to a preference update for a single veteran.
I have implemented the lambda handler to process only the first element in "bios" and to log a warning if the array has more than one element.  Issue #766 will set up a monitor for these warnings.
The changes also refactor the lambda …

VA Profile - Remove list of returned values in PUT request

---

app/dao/dao_utils.py
app/dao/service_sms_sender_dao.py
app/models.py
app/service/service_senders_schema.py
app/service/sms_sender_rest.py
scripts/postman/notification-api.postman_collection.json
tests/README.md
tests/app/dao/test_service_sms_sender_dao.py
tests/app/db.py
tests/app/service/test_schema.py
tests/app/service/test_sms_sender_rest.py
tests/conftest.py

#748
These changes should implement all necessary endpoint and unit test changes to accommodate the addition of the sms_sender_specifics field in #746.  By volume, most of the changes are clean-ups I made during the process.
The only change I made to the Postman collection is changing the URL for deleting a ServiceSmsSender record.  I don't think this merits any sort of version change for the API because the path in Postman did not match what the API implements.  I merely corrected it.

VEText migration - Update API and Postman collections for SMS Sender

---

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py

[538](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-team/538)
Twilio needs a response that includes TWIML in order to NOT log errors in the twilio console.
In the body of the message, add the twiml xml doc
In the headers/content-type, set the text/xml value

Vetext incoming forwarder lambda hotfix for twilio response

---

.github/workflows/deploy_lambda_dev.yml

Part of the actions rework removed the ability to deploy lambda code to dev individually. This action re-enables that functionality. 
We have a `workflow_distpatch` that will run the build/deploy lambda job and only deploy the lambda code to dev. 
Fixes #793 
- This will be validated when it's merged into the default branch and allowed to be triggered.

#793 Allow for Manual Lambda Deployments to Dev

---

lambda_functions/va_profile_remove_old_opt_outs/va_profile_remove_old_opt_outs_lambda.py

Just added comments, changed it to not use the root logger, and ensured the connection gets closed at the end.
Timeout issue is infra-related.
[Cloudwatch log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fproject-dev-va-profile-remove-old-opt-outs-lambda/log-events$3Fstart$3D1660246157000$26filterPattern$3D$26end$3D1660246158000) of it working.

#777 Resolve Lambda Timeout Related to Removing Opt-outs

---

app/va/vetext/client.py

Discussion with VeText led to an agreement to increase the timeout for push notifications to 11 seconds.

#800 Updated timeout per VeText agreement.

---

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py

Necessary change to differentiate between connection and byte reads. The only change is to change the timeout from a scaler to a tuple, with associated timeout values. 
Documentation related to the change: 
- https://requests.readthedocs.io/en/latest/user/advanced/#timeouts
- https://requests.readthedocs.io/en/latest/api/?highlight=requests.post#requests.request (see timeout param)
Fixes #819 
This is an intermittent issue regarding VeText's endpoint. We do not have a way to replicate this for testing locally. This will be tested when we start hammering the endpoint tomorrow.

Modified the timeout to specify connection and byte read timeouts.

---

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py

This is an emergency PR. All timeouts are going to the dead letter queue due to a variable that's not set if we hit an exception.
- [x My code follows the style guidelines of this project

Fixed exception errors

---

lambda_functions/va_profile/requirements-lambda.txt
lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
requirements_for_test.txt
tests/lambda_functions/va_profile/test_va_profile_integration.py

#810
See the ticket for the long description.  The short version is that the lambda needs to be able to handle the request body delivered as a stringified JSON object.  I also made changes to retrieve all necessary values from the SSM Parameter Store in one call.
These changes get POST functionality working.  Other ticket addresses the still-broken PUT functionality.  Included herein:
1. Alter opt-in/out lambda to handle the payload delivered by the load-balancer (stringified JSON object).
2. Make only one call to SSM Parameter Store to retrieve all necessary values.
3. Use communicationChannelId 1 instead of 2.  (Change in what Profile previously communicated to us.)
4. Pin the version of the cryptography package used with lambdas.

VA Profile integration: Alter opt-in/out lambda to handle the payload delivered by the loadbalancer.

---

cd/application-deployment/prod/vaec-api-task-definition.json
cd/application-deployment/prod/vaec-celery-task-definition.json

This was updated a week or so ago with VeText as a test and left in place to see how it handled.
We would like to leave it in place indefinitely. This change is already in prod. A branch was cut off what was in prod with just this one change, then pushed through to deployment.
This has been in prod for about a week.

Updated vetext url.

---

.talismanrc
lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
scripts/run_tests.sh
scripts/run_user_flows.sh
tests/README.md
tests/lambda_functions/va_profile/README.md
tests/lambda_functions/va_profile/test_va_profile_integration.py

As described in the ticket.  While unit testing, I discovered that the executable "py.test" is outdated and replaced those instances with "pytest".
Closes #863.

#863 Modify VA Profile lambda to support integration testing

---

lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
tests/lambda_functions/va_profile/test_va_profile_integration.py

During QA/integration testing, the POST response is supposed to contain the PUT request body.  This is for convenience when making POST requests from a command line client, such as curl, so the user doesn't have to check the CloudWatch logs to see the PUT body.
The PUT body wasn't showing up, and the reason is that AWS Lambda requires the lambda handler return value to include an HTTP response body in a "body" attribute with a stringified value.  This is [not well documented](https://docs.aws.amazon.com/lambda/latest/dg/python-handler.html#python-handler-return).
Using curl in the EC2 bastion host terminal:
```
< HTTP/2 200
< server: awselb/2.0
< date: Mon, 24 Oct 2022 21:21:48 GMT
< content-type: application/json
< content-length: 78
<
* Connection #0 to host dev.api.notifications.va.gov …
```

#863 VA Profile integration: Revise the format of the POST response returned during QA testing

---

.talismanrc
lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
lambda_functions/va_profile_remove_old_opt_outs/va_profile_remove_old_opt_outs_lambda.py

As described in the ticket.
Deployed:
[Opt-In/Out](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3322621949)
[Remove old](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3322729389)
I manually tested calling the opt-in/out lambda via Lambda console: [CloudWatch logs](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fproject-dev-va-profile-opt-in-out-lambda/log-events/2022$252F10$252F25$252F$255B$2524LATEST$255D7442083e2f314ee5952aabe45a07c805)
You can verify in the Lambda console "environment variables" tab that the database URI is no longer part of the execution environment:
[Opt-In/Out](https://console.amazonaws-us-gov.com/lambda/home?region=us-gov …

#902 Lambda functions should read the database URL from SSM Parameter Store

---

.github/workflows/db-downgrade.yml
.github/workflows/deployment.yml
.github/workflows/dev_deploy.yml
.github/workflows/release_trigger.yml
.github/workflows/tag_trigger.yml
scripts/tag_git_dev.sh
scripts/tag_git_staging.sh

Github actions updated according to the guide, `$GITHUB_OTUPUT` is used to replace `set-ouput`. No `set-state` in the code base.

Github actions 'set-output' updated

---

.talismanrc
lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
tests/lambda_functions/va_profile/test_va_profile_integration.py

My implementation had the possibility of raising KeyError because I referenced an attribute in a dictionary created from a POST request body.  It could be the case that the POST body is missing required attributes.  I replaced the bracket syntax with the dict.get method call that does not raise KeyError.
Fixes #918
I updated and ran unit tests.

#918 VA Profile integration: KeyError raised when the sourceDate attribute is missing from the POST body

---

.github/workflows/db-downgrade.yml
.github/workflows/deploy_lambda_dev.yml
.github/workflows/dev_deploy.yml
.github/workflows/load-test-email-delivery-time.yaml
.github/workflows/load-test-sms-response-time.yaml
.github/workflows/user_flows.yml

Changed all workflow actions, removing github.events based on the documentation below:
[Documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)
>Note: The workflow will also receive the inputs in the github.event.inputs context. The information in the inputs context and github.event.inputs context is identical except that the inputs context preserves Boolean values as Booleans instead of converting them to strings.
The `inputs` context is [only available](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context) in workflow dispatch or with reusable workflows. Alternatively we could have evaluated the string, but a choice was made to use the right tool for the right job (inputs context for `workflow_dispatch` and …

#925 Changed inputs for if blocks

---

.github/workflows/lambda-functions.yml
lambda_functions/va_profile/requirements-lambda.txt
lambda_functions/va_profile_remove_old_opt_outs/requirements-lambda.txt
lambda_functions/va_profile_remove_old_opt_outs/va_profile_remove_old_opt_outs_lambda.py

[vanotify-infra 438](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/438) created a lambda layer containing the Python package psycopg2-binary version 2.9.5 and added this layer to the two lambdas associated with VA Profile integration.
The changes for this PR remove psycopg2-binary from the lambda build process.  This should not have any impact on functionality.
I also discovered during testing that I recently broke va_profile_remove_old_opt_outs_lambda.  I made a couple of changes under this PR that allowed me to run that function in Lambda console, which is enough to verify that the code is able to import psycopg2-binary from the layer, but I will create a new ticket for fixing the problem.
Closes #855.
We packaged …

#855 Modify the deployment packaging for VA Profile integration lambdas.

---

lambda_functions/va_profile/va_profile_opt_in_out_lambda.py

These changes remove comments as described in the ticket.
Closes #934.

#934 Remove inaccurate comments from va_profile_opt_in_out_lambda.py

---

app/celery/reporting_tasks.py
app/dao/fact_notification_status_dao.py
lambda_functions/nightly_stats_bigquery_upload/nightly_stats_bigquery_upload_lambda.py
tests/app/celery/test_reporting_tasks.py
tests/app/dao/test_fact_notification_status_dao.py
tests/lambda_functions/nightly_stats_bigquery_upload/test_nightly_stats_bigquery_upload.py

This change was to add a new column called `channel_type` in the nightly statistics table so we can categorize the messages in datadog. 
Fixes #867

#867 BigQuery Update New Column

---

documents/openapi/openapi.yaml

Email Notification Endpoint API Doc updated, example for `recipient_identifier` added.
Fixes #856

#856 API Doc update - Email Notification Endpoint

---

documents/openapi/openapi.yaml

SMS Notification Endpoint API Doc updated, example for `recipient_identifier` added.
Fixes #858 

#858 Update API Docs: SMS Notification Endpoint

---

.talismanrc
app/celery/provider_tasks.py
app/celery/scheduled_tasks.py
app/clients/__init__.py
app/config.py
app/dao/provider_details_dao.py
app/dao/templates_dao.py
app/delivery/send_to_providers.py
app/notifications/process_notifications.py
app/notifications/rest.py
app/provider_details/provider_service.py
app/provider_details/switch_providers.py
lambda_functions/user_flows/test_retrieve_everything.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/conftest.py
tests/app/dao/test_provider_details_dao.py
tests/app/delivery/test_send_to_providers.py
tests/app/provider_details/test_provider_service.py

These changes modify the code that selects an SMS provider according to this process:
1. Use the template's provider_id first.
2. Use the service's provider_id if the template's provider_id is None.
3. Ensure any other provider determinations are not made.
The 3rd item is the change.  The first 2 steps already existed in the code, which I modified for readability and PEP8 compliance.  The logic for e-mail should not change.
My initial draft resulted in a failing user flow test for sending e-mail.  The bulk of the changes in this PR are comments, annotations, and minor code clean-up I made while crawling through the code base line by line to try to figure out what the existing code does and how the test failed.  The bulk of the substantial changes are in …

#944 Modify Provider selection logic

---

lambda_functions/user_flows/test_retrieve_everything.py

The tickets prescribes updating provider selection logic for e-mail, but I don't think any changes are necessary for that after my previous [changes for 944](https://github.com/department-of-veterans-affairs/notification-api/pull/950).
The ticket also prescribe database changes that include deactivating the Govdelivery provider.  The changes in this PR update user flows tests to accommodate that change.
Fixes #975
This is a non-breaking change to tests in response to a change in the development environment.
I deployed the branch and got user flows tests to pass.

#975 Update provider selection logic for e-mail

---

load_testing/send_sms_load_test.py

To run the Locust load test for sms, changes were required of the test to fix the JWT sent in the POST request and the phone number used to an Amazon simulated number.
- Changes the function annotation for the create JWT function from `-> bytes` to `-> str`, since the method returns a string
- Updates the headers sent to just use the returned JWT and adds a Content-Type header
- Changes the phone number to an Amazon simulated number.

#663 fix JWT and change phone number

---

.github/workflows/dev_deploy.yml
.github/workflows/tag_trigger.yml

This branch is so we don't have to keep sidestepping this issue. When [964](https://github.com/department-of-veterans-affairs/notification-api/issues/964) is resolved we will revert this change.
[Deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3633673099)

Temporarily Removed Twistlock Scans

---

cd/application-deployment/perf/vaec-api-task-definition.json
cd/application-deployment/perf/vaec-celery-beat-task-definition.json
cd/application-deployment/perf/vaec-celery-task-definition.json

Perf was showing an error when attempting to send SMS that showed the incorrect pinpoint id (it was using staging). This is changed to use the correct project id:
Fixes #979 
It was attempting to send SMS with the wrong Pinpoint Project ID, so to test we updated the ID and pushed it to perf. The messages that failed to send then actually sent thanks to Celery's retry policy on those tasks.
No new tests were added. This is a configuration for the system and I'm not sure it needs them. Welcome to your thoughts on the matter @cris-oddball

#979 Updated AWS_PINPOINT_APP_ID to use the correct id

---

.github/workflows/load-test-sms-response-time.yaml

Since the phone number for the test was changed to an Amazon simulated number, there is a cost incurred with each sms sent to that number. To ensure that someone doesn't randomly run an expensive sms load test, the defaults are modified such that the runtime is 10 seconds with 1 concurrent user.  
Fixes #989 

#989 modify defaults for locust sms test

---

.github/workflows/dev_deploy.yml
.github/workflows/tag_trigger.yml
.github/workflows/twistlock.yml

Fixes #964 
- Updated the name of the project from  VaNotify
- Restored the Twistlock action for Deploy to Dev
tested by 
- deployed [Infra code change](https://github.com/department-of-veterans-affairs/vanotify-infra/pull/481) such that the base url and the twistlock client are updated on the EC2 instance
- deployed this api branch to dev and [confirmed that the twistlock scan actually ran](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3660901717/jobs/6188601200) (and found vulnerabilies!)

964 update twistlock project name and restore action

---

Makefile
app/inbound_number/inbound_number_schema.py
requirements-app.txt
tests/app/inbound_number/test_rest.py

Alter inbound number schema to require url_endpoint whenever self_managed is true.  I also documented and ignored a new vulnerability Safety identified for SQLAlchemy, which is not something we can upgrade without significant refactoring.
Fixes #932
I manually tested in a Python interpreter, using https://www.jsonschemavalidator.net/, and by writing new test cases that pass.

#932 Alter inbound number schema logic

---

.github/pull_request_template.md

Removing auto-close feature from PR
"[Fixes](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)" closes the issue automatically. We still want to link the issue, so this PR just removes the auto-close feature.

Removed fixes from PR

---

.github/workflows/lambda-functions.yml
lambda_functions/two_way_sms/requirements-lambda.txt
lambda_functions/vetext_incoming_forwarder_lambda/requirements-lambda.txt

This is a companion ticket to [vanotify-infra 480](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/480), which creates a lambda layer for the "requests" Python package.  These changes modify the packaging actions for the two-way-sms and Vetext lambdas so as not to zip Python dependencies.  The layers provide everything necessary.
#1017 
This is a change to lambda packaging.
I [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3733202478) all lambdas to dev and verified [here](https://us-gov-west-1.console.amazonaws-us-gov.com/lambda/home?region=us-gov-west-1#/functions/project-dev-vetext-incoming-forwarder-lambda?tab=code) and [here](https://us-gov-west-1.console.amazonaws-us-gov.com/lambda/home?region=us-gov-west-1#/functions …

#1017 Modify the packaging actions for the two-way-sms and Vetext lambdas

---

app/clients/sms/twilio.py

When our twilio client is used to initiate an SMS send, it includes a callback URL for delivery status. That callback URL is used by Twilio to deliver delivery statuses for that particular message.
The issue is that the callback URL that is being used uses our notifications.va.gov address, which is not accessible to public internet. This is result in 500 errors in Twilio for EVERY SMS request that goes through Notify that uses Twilio.
[#1034](https://github.com/department-of-veterans-affairs/notification-api/issues/1034)

1034-Twilio-Callback-URL-Bugfix

---

app/notifications/validators.py
tests/app/notifications/test_validators.py
tests/app/service/test_send_one_off_notification.py
tests/app/v2/notifications/test_post_notifications.py

Update the SMS API validation exceeding character limit behavior so the HTTP response is 201 instead of 4xx.
The changes also include some clean-up recently made in other files:
json.loads(response.get_text(...)) --> response.get_json()
'sms' | 'email' | 'letter' --> SMS_TYPE | EMAIL_TYPE | LETTER_TYPE (which are constants defined in models.py)
#1041

#1041 SMS Char Limit Changed to Warning

---

lambda_functions/va_profile/va_profile_opt_in_out_lambda.py

As previously implemented, the VA Profile integration lambda used the certificate chain associated with the Notify environment's load-balancer to verify the certificate for the VA Profile server to which Notify makes a PUT request.  This worked because Notify and Profile used certificates with the same CA signatures, but it broke when Notify updated their certificate.
These changes make use of a [new lambda layer](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/497) that includes all publicly available VA CA certificates.  With this new layer, Notify should again be able to verify Profile's certificate.
The changes contain a workaround.  [Creating the SSL context](https://docs.python.org/3.8/library/ssl.html#ssl.create_default_context) using the "capath" parameter …

#1061 Update the VA Profile integration lambda to accommodate new certificates

---

app/celery/process_pinpoint_receipt_tasks.py
app/dao/notifications_dao.py
app/models.py
documents/openapi/openapi-with-push.yaml
documents/openapi/openapi.yaml
migrations/versions/0355_sms_billing.py
tests/app/celery/test_process_pinpoint_receipt_tasks.py
tests/app/v2/notifications/test_get_notifications.py

These changes add billing related columns to the Notification definition and, for SMS notifications, persist this data as returned via AWS Pinpoint "event streams".
I updated the Notification response definition and GET examples in OpenAPI.  Changes for Postman are not applicable.  I'm you import the OpenAPI files into Postman, you will only be able to see the first example.  To see all examples, visit the [Swagger Editor](https://editor-next.swagger.io/), select "Import URL" from the "File" menu, and enter the [URL for a raw spec file](https://raw.githubusercontent.com/department-of-veterans-affairs/notification-api/1049-cost-total-message/documents/openapi/openapi.yaml).
Deployed: https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3963884407
#1049

#1049 Populate SMS cost and segments count for notifications

---

.github/workflows/build.yml
.github/workflows/twistlock.yml

#1090 
hotfix for latest twistlock merge due to a confusion with a syntax change
Because build.yml uses
```
gh workflow run -r master -F image-tag=${{ inputs.ref }}_${{ inputs.environment }} twistlock.yml
```
this would cause a twistlock fail.  So, I ran twistlock manually and it's now running fine:
**Twistlock will fail because build.yml is calling twistlock from the master branch**
- In the [Github Actions Syntax documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions), none of the inputs use the github.event syntax, though previously this may have been the case. 
- In the [Events the Trigger Workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs) doc, it says to preserve boolean values …

hotfix for latest twistlock merge - syntax fix

---

.github/workflows/dev_deploy.yml
.github/workflows/user_flows.yml

#1082
`Deploy to Dev ` should be configured to not run User Flows if the environment to deploy to is the Perf environment. It presently does not run User Flows in staging or prod.
**GIVEN** I want to deploy to perf under special circumstances
**WHEN** I deploy the code using the `Deploy to Dev` action
**THEN** It does not run User Flows in perf
-   [x] Update `dev_deploy.yml `
-   [x] Update `user_flows.yml `
-   [x] Test Deploy to Dev push to perf, validate that User Flows does not run
-   [x] My changes generate no new warnings
-   [x] QA

#1082 Remove User Flows for Perf Deploy

---

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py

#939 #1111 
This PR should resolve both bug tickets we were having in Twilio by returning a simple status code. Removed the twiml response and simply gave it an empty `Response` tag.

#939 and #1111 VeText 502

---

app/celery/letters_pdf_tasks.py
app/celery/process_ses_receipts_tasks.py
app/clients/email/govdelivery_client.py
app/clients/performance_platform/performance_platform_client.py
app/cronitor.py
app/notifications/utils.py
app/template/rest.py
app/user/rest.py
app/va/mpi/mpi.py
app/va/va_onsite/va_onsite_client.py
app/va/va_profile/va_profile_client.py
lambda_functions/user_flows/steps.py
lambda_functions/user_flows/test_retrieve_everything.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/celery/test_process_ses_receipts_tasks.py
tests/app/test_cronitor.py

Supply a timeout value with all HTTP requests made using the Python "requests" package.  This should clear the associated code scan failures described in the ticket.  In some instances, I slightly modified the exception handling because a timeout raises an exception.  Note that requests.RequestException is the parent class of all exceptions raised in the requests package.
[timeout reference](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=timeout)
I also cleaned up some of the logging, as we have been doing when we encounter it.
#1134

#1134 Supply a timeout value with all requests calls

---

app/__init__.py

This is just a quick fix to address bandit failing code scans with the error in the title. 
#1189
Code scan now passes.

#1189 BUG: Standard pseudo-random generators are not suitable for security/cryptographic purposes

---

app/celery/service_callback_tasks.py
tests/app/celery/test_service_callback_tasks.py

Status reason was coming through as the entire status_update object because it was missing a lookup on the dictionary. Additionally, `status_reason` and `provider` were supposed to be permanently added to the callbacks but there was logic to only add them if they existed. Changed the logic to set the `status_reason` to None if it's not set and to set `provider` to `pintpoint` if it's not set.
Code [pushed to Dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4578628254). Verified fields are there. 
And no hiccups with our existing pinpoint stuff:

Adjusted Payload Sent in Callbacks to Services' Endpoints

---

app/clients/sms/twilio.py
tests/app/clients/test_twilio.py

The message passed into the translate_delivery_status method is an b64 encoded string.  It's b64 encoded in the lambda that enqueues the message on the SQS that feeds the ECS Delivery status task.  The callback that gets made needs to send the same message that is sent from Twilio.  That message is a URL encoded string that is encoded in the b64 message.  
This change passes the decoded message back as the payload for the service callback.  
#1209 
Deployed to dev and tested to confirm that callback is now a URL encoded string.
Added a unit test that verifies the returned message is the decoded URL encoded string.

#1209 decoded provider payload from twilio

---

.talismanrc
requirements.txt

Update requirements.txt to use a newer version of notification-utils that contains a [hotfix for logging errors](https://github.com/department-of-veterans-affairs/notification-utils/commit/e5d5a30479b20041503eaa901eec5fce102944cb).  This relates to, but does not close, #1222.
This is just a dependency upgrade to use a 2-line change in notification-utils that catches all exceptions.

#1222 Update requirements.txt to use a newer version of notification-utils

---

app/celery/process_delivery_status_result_tasks.py
app/celery/process_pinpoint_receipt_tasks.py

When a status update callback cannot find the associated notification in the database for 5 minutes, log this condition as "critical" rather than "warning".
#1217 
I have not tested this other than running unit tests.  It's just a log level change.  We will make sure the level is "critical" during the QA check.

#1217 Change a logging call from "warning" to "critical"

---

README.md
ci/Dockerfile
ci/Dockerfile.local

I upgrade the version of Alpine Linux used in our app images from v3.15 to v3.17 and updated existing documentation with the new "end of life" date.
#1198

#1198 Upgrade the app image to use Alpine 3.17

---

app/celery/celery.py
scripts/run_celery.sh

This is a simple fix to make the celery worker kick off under the `exec` command. This ensures that the PID is transferred to the celery worker, so the `SIGTERM` signal is actually received. It was tested and observed that the `SIGTERM` does not pass through celery without calling with `exec`.
This does not fix the connection timeout but should prevent the task from terminating before completion.
#1251 
This was [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5007818954) to dev. It was observed that the hooks were being called, as shown in our logs (documented in #1251). Forced redeploy showed that the workers were receiving `SIGTERM` as expected. Prior to this change the hooks were not being called. …

#1251 Graceful Shutdown For Celery Tasks

---

README.md
ci/Dockerfile
ci/Dockerfile.local

Alpine v3.16 uses OpenSSL v1.1.1, whereas Alpine v3.17 uses OpenSSL v3.0.8.  The newer OpenSSL version causes problems with our Twilio integration until we can upgrade the "requests" and "urllib3" Python packages. #1284
#1284 
@cris-oddball Deployed this branch to Perf and tested.

#1284 Use Alpine Linux v3.16 for the Docker image

---

.github/workflows/lambda-functions.yml
lambda_functions/nightly_billing_bigquery_upload/requirements-lambda.txt
lambda_functions/nightly_stats_bigquery_upload/requirements-lambda.txt

These changes alter some lambda function packaging to rely on lambda layers for dependencies.  The affected lambda functions are the two for nightly stats generation and the two for VA Profile integration.  The stats-related layer was created by [vanotify-infra 568](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/568).
The changes for VA Profile integration are a reintroduction of changes made in [c576a0e](https://github.com/department-of-veterans-affairs/notification-api/commit/c576a0e3eaa4e64b0be340d75fb5fc6827450001) that were inadvertently reverted by [caf6d6f](https://github.com/department-of-veterans-affairs/notification-api/commit/caf6d6f104ab65c0aa17197b314888290484010e#diff-701410510466de561d2b481763cd324e1cba4ff947f85447ff6a6ba55086bfeb).
The only top …

#1270 lambda packaging for nightly stats and VA Profile integration

---

app/models.py
migrations/versions/0358_default_send_field.py
tests/app/communication_item/test_rest.py

These changes add the boolean column `default_send_indicator` to CommunicationItem table with a default value of True and modify an existing unit test.
#1252

#1252 Add the default_send_indicator column to the CommunicationItem table

---

app/celery/celery.py

The scope of this ticket was updated to just standardize the format of the celery messages for success and failure. 
#1277
This is tested by sending a message or doing something that will trigger a celery task to run. We can then check the cloudwatch logs for the messages that start will "celery task success" and "celery task failure" to check how long they ran.

1277 Implement Celery Serverhooks

---

gunicorn_config.py
requirements-app.txt
requirements.txt

Configure Gunicorn's keepalive value to 70 seconds.  There is no associated ticket.
https://docs.gunicorn.org/en/stable/settings.html#keepalive
These changes also perform a patch upgrade of Flask from v2.2.3 to v2.2.5 because the former has a vulnerability flagged by Safety.  The patch upgrade is explicitly to fix the vulnerability. There's no risk.

Configure Gunicorn's keepalive value to 70 seconds

---

.talismanrc
app/communication_item/communication_item_schemas.py
app/communication_item/rest.py
app/models.py
migrations/versions/0359_communication_items_unique.py
scripts/postman/notification-api.postman_collection.json
tests/app/communication_item/test_rest.py
tests/app/conftest.py
tests/app/db.py

These changes:
- Complete the CRUD implementation for the CommunicationItem model
- Include a migration to force uniqueness for two CommunicationItem columns
- Update the Postman collection to include all CommunicationItem routes
- Removes redundant lines in .talismanrc
I initially planned to make database queries using the newer SQLAlchemy v2.0 query syntax.  (We use version 1.4, which supports the new and legacy syntax.)  However, I came to understand that the syntax used throughout the app (i.e. ModelName.query.get(<id>), etc.) is actually provided by [flask-sqlalchemy](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/quickstart/#query-the-data), which [supports SQLAlchemy >= 1.4.18](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/changes/#version-3-0-0).
#1253

#1253 Added routes and unit tests for CommunicationItem

---

app/celery/lookup_recipient_communication_permissions_task.py
app/dao/communication_item_dao.py
app/va/va_profile/va_profile_client.py
tests/app/celery/test_lookup_recipient_communication_permissions_task.py

This PR is to add logic that will change when notifications are sent depending on the "default send" preference set in the communication item attached to the template. 
#1227
Deployed to dev and notifications sent with below parameters.
User’s VA Profile ID 43627 has no selection for any communication items
User’s VA Profile 112491 has the above communication items set to “allowed”: “true”
User’s VA Profile 37459 has the has the above communication items set to “allowed”: “false”

#1227 Explicit Logic for Communication Items

---

documents/openapi/openapi.yaml
scripts/postman/notification-api.postman_collection.json

These changes:
1. Add all CommunicationItem routes to [our OpenAPI specification](https://github.com/department-of-veterans-affairs/notification-api/tree/master/documents/openapi)
2. Make a minor tweak to a default request body in the Postman collection that I should have made for #1253
3. Use `nullable: false` to create documentation that shows up in the Swagger Editor.  `nullable` isn't part of the OpenAPI or JSON Schema specifications, but our specification uses it extensively.
These changes do not make any updates to [openapi-with-push.yaml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi-with-push.yaml), which is not discussed in README.md and does not seem to be in use.
Useful documentation and tools:
1. [OpenAPI …

#1268 Updated the OpenAPI specification and Postman collection for CommunicationItem

---

.github/workflows/release_trigger.yml

This PR addresses an issue where the "pre-release" trigger for GitHub Actions is not working as expected in our `.github/workflows/release_trigger.yml` file. To mitigate this issue, we're changing the trigger event from `release` and `pre-release` to `published`. This change aims to automate the deployment to staging whenever a pre-release is published, eliminating the need for manual deployment.
The only way to accurately test this change is by merging it to the master branch and then creating a test pre-release. Hence, it requires a fast-track review and approval process to validate the fix.
#1214
Due to the nature of this change, the only way to verify the fix is by merging this PR into the master branch, creating a pre-release, and publishing it to trigger the GitHub Actions workflow. …

#1214 Fix Pre-release Trigger for GitHub Actions

---

app/celery/common.py
app/celery/provider_tasks.py

This fixes an exception that the utils repo was throwing due to a bug. In the API the Celery `autoretry_for` code replaced anywhere the previous team(s) called `task.retry()`. This in itself was fine but we increased the retry time to 24 hours. This caused a little-known feature to raise an infinitely growing number of requests. Every 4 hours and 15 minutes the system checks for any notifications in the "created" status and tries to send them again. This happens every 15 minutes. There is another method that moves `created` tasks to `technical-failure` if they are not processed in time, so there was a second exception being thrown for those. Those were a result of the utils bug, so nothing was changed for that. 
When retries were limited to 4 hours that was not an issue. When we gave it …

Exception Retry Hotfix

---

.github/workflows/tests.yaml
README.md
ci/docker-compose-local-migrate.yml
ci/docker-compose-local.yml
ci/docker-compose-test.yml
ci/docker-compose.yml
tests/app/dao/test_services_dao.py

Upgrade Postgres containers from v11 to v15.  This is part of [vanotify-infra 528](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/528).
I made a minor change to one unit test that looks for specific error output from the database.  The newer version of Postgres slightly modifies this output by providing more information.

Upgrade Postgres containers from v11 to v15

---

app/celery/common.py
app/celery/provider_tasks.py

This hotfix enables us to catch `AttributeError` and `RuntimeError` exceptions thrown by the `deliver_sms_with_rate_limiting()`, `deliver_sms()`, and `deliver_email()` methods. The cause of these exceptions are being investigated still, but a fix should be coming. This is a hotfix so that regardless of Attribute or Runtime error we do not retry, as those are errors that should never allow retries. There is a related bugfix being worked to address the cause of the AttributeError appearing in the first place.
#1419 
This same code was deployed to stop the flood of retries that were happening. A [second deploy](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5868488933) was made as well. QA Regression ran against the Dev Deploy and all tests passed.

#1419 Hotfix AttributeError and  RuntimeError catch

---

.talismanrc
app/celery/contact_information_tasks.py
app/celery/provider_tasks.py
app/va/va_profile/va_profile_client.py
tests/app/celery/test_contact_information_tasks.py

These changes address the presence of an abundance of instances of `'NoneType' object has no attribute 'replace'` in the logs and a subsequent spike in the size of the "send email" queue.  The problem seems to occur when making POST request to send a notification using a recipient ID, which results in a query to VA Profile.  The response from Profile is used to set the "to" string attribute of the Notification instance.  If the request to Profile times out, "to" remains defaulted to None, and that causes the AttributeError downstream.
These changes log the timeout exception in the Profile client, where it occurs, and handles the exception in the relevant Celery task that uses the Profile client.  I treated a timeout as a retryable exception, which means it should remain in the Celery …

#1419 Halt Celery processing to send a notification if VA Profile times outand trigger a retry

---

app/celery/provider_tasks.py
app/notifications/validators.py
tests/app/celery/test_provider_tasks.py
tests/app/notifications/test_validators.py

It was missed that `autoretry_for` was not added to sms with rate limiting.
This PR adds it to `deliver_sms_with_rate_limiting` and gives it up to a 2 second initial delay.
https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.retry_backoff
As far as we can tell this has not impacted any services
This tells me that the unit tests were not initially sufficient for retries, otherwise it should have failed (retry tests for all other changes required large overhauls). 
This code (pre-autoretry_for) never had any unit test coverage:
So when the logic was changed to what it is now, it didn't fail unit tests because there were none to fail. The existing rate limiting retry logic was left in-place because it used an equation to calculate retry time (`retry_time = …

Hotfix AutoRetry For Rate Limiting SMS Deliveries

---

.github/workflows/build.yml

This PR addresses the stability issues with the Twistlock EC2 instance, which frequently faced issues during scans. We've improved the configuration of the `utility-twistlock-scanner` EC2 instance to ensure it remains stable and reliably scans our container images on every deploy.
Specifically this is simply to re-add twistlock back into our dev deploy workflow
Addresses the notification-api aspect of [#626](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-infra/626)
- Twistlock has stayed standing for multiple days and multiple tests (beyond 5).
Relevant resources:
- [twistlock-init.cfg](https://github.com/department-of-veterans-affairs/vanotify-infra/blob/master/cd/utility-infrastructure/twistlock-init.cfg)
- …

626 Twistlock Re-added

---

Makefile
app/authentication/auth.py
app/v3/__init__.py
app/v3/notifications/notification_schemas.py
app/v3/notifications/rest.py
documents/openapi/openapi.yaml
requirements-app.txt
tests/app/v3/notifications/test_notification_schemas.py
tests/app/v3/notifications/test_rest.py

This is a revision to address QA findings after I merged [PR 1430](https://github.com/department-of-veterans-affairs/notification-api/pull/1430).  These changes:
- Address schema validation failures
- Utilize the Python "phonenumbers" package to test for "possible" and "valid" phone numbers.  (See "Example Usage" [here](https://pypi.org/project/phonenumbers/).)
- Restore the "scheduled_for" field, and validate that the value is neither in the past nor more than one calendar day in the future.  This is easy to change later if necessary.  It isn't entirely obvious from the v2 implementation what the permissible range is supposed to be, and none of our customers are using this functionality now.
- Customizes the validation error response body for requests that provide neither (phone number …

#1360 POST /v3/notifications/ revision

---

app/models.py
migrations/versions/0362_add_service_field.py

Adds new field to the `services` table.
- `p2p_enabled` optional boolean field
This new field will allow the portal to track and update P2P status on a service by service basis. Thanks to @MarchandMD for pairing on this with me.
issue [1118](https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/vanotify-team/1118)

Add p2p_enabled field to services table

---

app/models.py
migrations/versions/0363_add_reply_to_inbox.py

Add `reply_to_inbox` database table for tracking Reply-to Inboxes related to each service.
[issue](https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/notification-portal/1362)
- Tested locally and was able to upgrade and downgrade without any issues.
- Deployed to [migration to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6276595747) and successfully [rolled back](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6276798370).

Add Reply-to Inbox Table

---

documents/openapi/openapi.yaml

Correct the v2 and v3 Swagger examples for POST e-mail notifications to show "email_address" instead of "email".  The former is the actual attribute name.  Also correct invalid uses of the "format" specification for strings.  There is no associated ticket.
- [JSON Schema string formatters](https://json-schema.org/understanding-json-schema/reference/string.html#format)
There is no "phone_number", "url", "base64", or "auth type" formatter.  The e-mail address formatter is "email"; not "email_address".  The datetime formatter is "date-time"; not "datetime".
I pasted the OpenAPI document into [Swagger Editor](https://editor-next.swagger.io/) and manually inspected them.

Swagger corrections

---

.github/workflows/dev_deploy.yml
.github/workflows/prerelease_trigger.yml
.github/workflows/tag_trigger.yml

Running the regression against the public endpoints is resulting in wholesale timeouts on tests or 400s. Removing the step from the three workflows using it and looking for a better answer.
Hotfix
This removes the run-qa-suite step from deploy to env, tag push to perf and the pre-release to staging.
- This basically reverts recent changes back to the way the workflows used to behave. The code needs to be merged before testing.
- Testing will be that on these actions, the QA suite does …

Hotfix - remove run-qa-suite from deploy, tag and pre-release

---

.talismanrc
app/celery/v3/notification_tasks.py
app/config.py
app/models.py
app/v3/__init__.py
app/v3/notifications/rest.py
tests/app/celery/v3/test_notification_tasks.py
tests/app/conftest.py
tests/app/v3/notifications/test_rest.py

These changes for v3 notification logic:
- Implement a 501 (not implemented) response if a user includes "scheduled_for" in the request data
- Include Celery tasks to send notifications with Pinpoint (SMS) and SES (e-mail)
- Include unit tests for the above
The changes are nowhere near feature complete, and this PR does not complete #1361.  I will author a new PR with additional changes that add error handling, which is necessary, among other reasons, to retry failed tasks when appropriate.
Many other tickets are necessary before v3 achieves anything resembling feature completeness or parity with v2.  There are a lot of TODOs in the code, and creating tickets for all of them now is not feasible.  Please trust that I'm working on all of it.
issue #1361 …

#1361 v3 basic send logic (part 1)

---

app/va/vetext/client.py
tests/app/v2/notifications/test_push_notifications.py

Talks with VEText let us know that if we make the connection we can consider the PUSH notification sent. This looks specifically for the read timeouts and does not raise a retryable exception if there was a read timeout. Services have been retrying these timeouts that VEText processes, which is leading to duplicate PUSH notifications.
issue N/A
Unit tests [pass](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6693640584/job/18185211368?pr=1519#step:8:8229). I can't force VEText to have a read timeout. [Deployment](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6693827458) was successful.

Hotfix to Return 201 on PUSH Timeout

---

app/celery/v3/notification_tasks.py
requirements-app.txt
tests/app/celery/v3/test_notification_tasks.py

We want to ensure V3 has feature parity with V2. Clients can send an SMS request with or without an sms_sender_id. If they send without, then we must look up the default sender assigned to the service and send the SMS from that sender.
issue #1504
- this was tested locally by modifying requests and records in database to simulate relevant conditions
- this was deployed to Dev and tested there by Nikolai and Cris
Latest deployment to DEV
https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6806916784

#1504 - Use the default SMS sender if one is not provided

---

Makefile

Hotfix to ignore Safety vulnerability 61893 (urllib3).
issue: N/A
This is a change to ignore a Safety scan issue.  If the branch passes the Safety check, it's good.

Hotfix to ignore Safety vulnerability 61893 (urllib3)

---

app/notifications/validators.py
tests/app/notifications/test_validators.py

Updated the appropriate code with a try/except block to catch the `KeyError` raised if an invalid country code (prefix) makes it all the way to the international lookup table.
issue #1525 
Ran and made modifications locally until it passed. [Regression tests](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/7341439249) pass. Created a test API key, [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7341332607) and validated it raised the error and returned the status code we expected:
Properly logs so we can help services:

#1525 [BUGFIX] KeyError Invalid Phone Number Prefix

---

app/celery/v3/notification_tasks.py
requirements_for_test.txt
tests/app/communication_item/test_rest.py
tests/app/test_cronitor.py

Removed extra decorator that prevented the Celery task from running.
Added some unrelated, but required, unit test fixes and locked pytest + moto to their last major versions due to breaking changes.
issue #1501 
Deployed and tested sending an email with v3. Succeeded.

#1501 [v3] Removed Extra Decorator

---

.talismanrc
app/va/vetext/client.py
cd/application-deployment/perf/vaec-api-task-definition.json
cd/application-deployment/perf/vaec-celery-task-definition.json

…ions
Add additional environment variables to Perf for push notifications.  Without these variables, push requests fail in Perf.  The changes are already in other environments.
I also manually added new Parameter Store parameters for Perf.  These parameters already exist for the other environments and were created manually for them as well.
issue #1523

#1523 Add additional environment variables to Perf for push notifications

---

.gitignore
app/models.py
documents/openapi/openapi.yaml
migrations/versions/0331_merge_service_apis.py
migrations/versions/0368_servicesmssender_columns.py

These changes:
1. add two new columns, "description" and "provider_id," to the service_sms_sender table, and include those new columns in the model's serialization method
2. modify migration 0331, which should have dropped table service_inbound_api
3. modify the OpenAPI documentation for ServiceSmsSender to include the new columns in GET and POST responses
I discovered the issue with migration 0331 when I created the new migration, and I will create a new ticket manually to drop the table in all environments.
The ticket specifies that modifying OpenApi docs is out of scope.  I did not modify any request body because the new columns are not valid request attributes until we change the schemas in a future ticket (see #1687), but the specs are out of sync with reality unless I change the …

#1685 New columns for ServiceSmsSender

---

lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py

Identified an opportunity for increased logging. This adds one more output to the logging statement in the event of a failed validation with the delivery status lambda.
issue N/A
Trivial change to logging. Verified with deployment

Hotfix - Added Event To Logging

---

lambda_functions/vetext_incoming_forwarder_lambda/twilio_signature_utils.py
lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py

Refactored the way SSM lookups are done because we have to grab 3 parameters. All are grabbed during the execution environment setup, so the decision was made to split them logically rather than request all during a single call. Wrote a new encryption method to setup encryption based on gathered SSM params.
Unit tests were problematic because the test dictionaries were being modified in the tests. Changed those to use a deepcopy so they were not affecting subsequent tests. Also, because the script invokes certain methods as part of the script being loaded in, you have to feed it fake variables first (the if block in those methods), then you can add real test values.
Added type annotations but was met with failures. Python 3.8 syntax is different than 3.10+. Decided to skip annotations for …

#1816 - Added Additional Auth and Encryption

---

.github/workflows/lambda-functions.yml

These changes remove the set-python action from the lambda-functions.yml workflow, which is a legacy step from when we used to bundle dependencies with lambda code upon deployment.  (We use layers now.)
issue #1839 
I [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/9897031716) the VA Profile Opt-in/out lambda to Dev from the master branch using this PR's branch for the workflow.  Then I verified in the Lambda console that everything is as …

#1839 Remove the set-python action from the lambda-functions.yml workflow

---

app/celery/common.py
app/celery/contact_information_tasks.py
app/celery/lookup_va_profile_id_task.py
app/celery/service_callback_tasks.py
tests/app/celery/test_contact_information_tasks.py
tests/app/celery/test_lookup_va_profile_id_task.py

Whenever a message reaches its final state, any associated callback functions should be called.  We noted that this was not always happening for failures related to VA Profile look-ups, and these changes amend the behavior.
These changes also remove a module specific "notification" fixture and replace it with the "sample_notification" fixture from tests/app/conftest.py.
These changes are also most of the solution for #1914.
issue #1800
I wrote new unit tests, ran the regression tests, and tried to send an SMS notification from Perf using VA Profile ID 1550938, which does not have an associated phone number.  The latter test obligated me to create a new callback in Perf for the VA Notify service that pings …

#1800 Delivery Status Callbacks: VA Profile lookup failures

---

app/celery/common.py
app/celery/contact_information_tasks.py
app/celery/lookup_va_profile_id_task.py
app/celery/service_callback_tasks.py
tests/app/celery/test_contact_information_tasks.py
tests/app/celery/test_lookup_va_profile_id_task.py

Reverts department-of-veterans-affairs/notification-api#1898.
This revert is due to callbacks not being triggered for messages with the status preferences-declined.

Revert "#1800 Delivery Status Callbacks: VA Profile lookup failures"

---

.github/workflows/deployment.yml
.github/workflows/dev_deploy.yml

Removed "environment" from various steps that did not signify the completion of a deployment to that environment. A deployment is only complete if it has passed the regression suite.
Reminder:
environment in the step sets the environment, whereas 
```
with:
environment
```
sets a string variable. All env string variables were left unchanged.
issue N/A
Deployed and watched PR dev deploy status to ensure it never went green at any step until the last. It remained like this:
until the regression step began, then it was in a pending state:
and finally an active deployment state:
Forgot to run the test with lambdas deployed, [so ran another deploy](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/10373916386/job/28720165412) …

HOTFIX - GHA "environment" Variable Pruning

---

cd/application-deployment/perf/vaec-celery-task-definition.json
cd/application-deployment/staging/vaec-celery-task-definition.json

This PR simply enables the feature flag in Perf and Staging. @k-macmillan coordinated with VA Profile to test that this feature is working in those environments. To see the work done to create this feature you can see [this PR](https://github.com/department-of-veterans-affairs/notification-api/pull/1889).
issue #1779 
- This was tested in Dev and proved to be working. We were waiting for VA Profile to enable their endpoint in these environments before turning the feature flag on here.
Here are the logs from testing when deploying to Perf and running the regression. The debug logs are for checking the feature flag, collecting data, and sending to VA Profile via the URL. There's also a log for the response we get VA Profile.

#1779 Enable VA Profile Email Status Sends in Perf & Staging

---

app/callback/queue_callback_strategy.py
app/celery/common.py
app/celery/contact_information_tasks.py
app/celery/lookup_recipient_communication_permissions_task.py
app/celery/lookup_va_profile_id_task.py
app/celery/onsite_notification_tasks.py
app/celery/provider_tasks.py
app/celery/service_callback_tasks.py
app/notifications/process_notifications.py
app/va/va_onsite/va_onsite_client.py
tests/app/celery/test_contact_information_tasks.py
tests/app/celery/test_lookup_recipient_communication_permissions_task.py
tests/app/celery/test_lookup_va_profile_id_task.py
tests/app/celery/test_provider_tasks.py

You probably will want the side-by-side diff view for this one.
Sending a notification involves the execution of a chain of Celery tasks.  At any point in this chain, a notification reaching a final state should trigger service callbacks, if any, which generally means calling the function `check_and_queue_callback_task`.
I audited the relevant Celery tasks to ensure that `check_and_queue_callback_task` is called when appropriate and found a number of instances where it was not called.  By volume, most of my changes are to unit tests and to logging statements to make them use the C-style syntax instead of f-strings.  I followed the style of the existing unit tests, which do a lot of mocking, rather than try to overhaul everything to be consistent with the TDD approach we recently …

#1800 Delivery Status Callbacks

---

app/celery/process_ses_receipts_tasks.py
app/celery/scheduled_tasks.py

Every day there are replays of notifications that have been stuck in "created" status, but the replay code does not log what notification id was stuck in created. This PR is to log the notification id so we can investigate further without having to resort to entering the database/BQ/etc.
issue N/A
Unit tests cover this part of the code. No logic has been changed.
SES results logs as expected:

HOTFIX - Log Replay Notification IDs

---

app/config.py
cd/application-deployment/dev/vaec-api-task-definition.json
cd/application-deployment/dev/vaec-celery-task-definition.json
cd/application-deployment/perf/vaec-api-task-definition.json
cd/application-deployment/perf/vaec-celery-task-definition.json
cd/application-deployment/prod/vaec-api-task-definition.json
cd/application-deployment/prod/vaec-celery-task-definition.json
cd/application-deployment/staging/vaec-api-task-definition.json
cd/application-deployment/staging/vaec-celery-task-definition.json

issue #1711 
[Spreadsheet Tracking Secret Keys and Environment Variables](https://docs.google.com/spreadsheets/d/1WYtI4Ky_p0ajRszOakhwV94EYzdDYS2XgQNEhX0fLIE/edit?gid=0#gid=0)
- Reviewed and removed all unused **secret keys** (Only secret keys, not environment) in the notification-api and notification-celery container from the 4 environments: dev, perf, staging, prod
- Ignoring the notification-celery-beats container.
- Documented old feature flags and create a ticket to remove them - [new ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1936)
- Documented all environment variables and created a ticket to move all envs into a shared env file - [new ticket …

#1711 - Remove unnecessary secret keys from task definitions

---

app/provider_details/provider_service.py

This PR updates the provider service to use the current_app logger instead of its current custom logger.
issue #1895 
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/10584578739) and inspected logs.  Dev has DEBUG logging, so they are there which verifies that the flask current app logger is working correctly.

#1895 Provider Service log level

---

.github/release.yaml
.github/scripts/prData.js
.github/scripts/prLabelSemver.js

This PR introduces the following changes:
* Simplifies our labeling scheme to map major, minor, and patch labels to their respective semver bumps
* Defaults to using a patch bump when no label is specified
* Allows multiple labels to be used on a PR (for example, minor and devops) to allow devs to continue using whatever labeling they want in addition to major, minor, and patch
* Cleaned up the `release.yaml` file to only create release notes for Major and Other categories
issue #1970 
Patch label:
Minor label:
Major label:
No labels (defaults to patch):
Major:
Minor:
NO LABELS (bumps to patch):
Multiple labels (minor and devops):

#1970 - Simplify labeling scheme to major, minor, patch

---

.talismanrc
app/callback/webhook_callback_strategy.py
app/celery/service_callback_tasks.py
app/dao/api_key_dao.py
tests/app/callback/test_webhook_callback_strategy.py
tests/app/celery/test_service_callback_tasks.py

Added a new method: `generate_callback_signature`. Added a new version of the callback data generation method. While doing TDD I attempted to use the existing method to generate a callback payload but found it required far more setup than the new way. Duplicated the existing method but built it a little different to replicate what our clients will receive.
issue #2001 
TDD, also, unit test generated a key and it was used to verify the signature generation is consistent and meets hmac-sha256 standards.

#2001 - Added signature generation via hmac-sha256

---

app/celery/process_delivery_status_result_tasks.py
app/celery/process_pinpoint_receipt_tasks.py
app/celery/process_ses_receipts_tasks.py
app/dao/notifications_dao.py
tests/app/celery/test_process_delivery_status_result_tasks.py
tests/app/celery/test_process_pinpoint_receipt_tasks.py
tests/app/celery/test_process_ses_receipts_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py

These changes ensure that a notification's "status reason" is always the empty string when the status is "delivered."
The underlying ticket cited a problem without an explicit way to reproduce it, so I went looking for problems.  These changes cover all code paths as far as I can tell without a specific problem to fix.
issue #2011
This is not easy to test because I don't know how to force providers to return a particular status.  I'm relying heavily on unit tests.

#2011 - Notification status and status_reason consistency

---

.gitignore
.talismanrc
app/callback/README.md
app/celery/nightly_tasks.py
app/celery/service_callback_tasks.py
app/commands.py
app/internal/rest.py
app/notifications/aws_sns_status_callback.py
app/notifications/process_client_response.py
tests/app/celery/test_service_callback_tasks.py

This work is connecting the pieces together for sending notification level callbacks. The app will now send callbacks to the endpoint indicated in the `callback_url` field when making a request by default. If there's nothing included in the `callback_url` field, it will default to the previous behavior.
issue #2012 
Logs captured from notification callback tests: (formatted for easier reading)
Debug log when successfully sending callback
```
Callback successfully sent for notification 8dd31563-0a11-4a3c-8a1e-2664958a4e2f,
url: https://dev.api.notifications.va.gov/internal/callback-test | status code: 200
```
POST response from internal endpoint
```
2024-10-10T19:50:11 app app INFO None 
"Generic Internal Request: METHOD: POST 
| ROOT_PATH:  
| PATH: /internal/callback-test 
| …
```

#2012 - Update Callback Logic for Notification Level Callback URL

---

app/celery/process_delivery_status_result_tasks.py
app/clients/sms/__init__.py
app/clients/sms/twilio.py
app/dao/notifications_dao.py
tests/app/celery/test_process_delivery_status_result_tasks.py
tests/app/clients/test_twilio.py

Saw many messages end up in a permanent failure or technical failure status with no status reason. This should not happen. Adjusted Twilio's delivery status to correctly fill that information in.
There was a bug with updating status_reason to None when a notification is put in the delivered status.
`if incoming_status_reason is not None` led to it ignoring the updated status_reason. The test mocked it out and the mock has been removed.
issue #N/A
Updated tests. Regression [passes](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11335358817).

HOTFIX - Added status reason to Twilio delivery status

---

.github/workflows/update-datadog-image.yaml
cd/application-deployment/dev/vaec-api-task-definition.json
cd/application-deployment/dev/vaec-celery-beat-task-definition.json
cd/application-deployment/dev/vaec-celery-task-definition.json
cd/application-deployment/perf/vaec-api-task-definition.json
cd/application-deployment/perf/vaec-celery-beat-task-definition.json
cd/application-deployment/perf/vaec-celery-task-definition.json
cd/application-deployment/prod/vaec-api-task-definition.json
cd/application-deployment/prod/vaec-celery-beat-task-definition.json
cd/application-deployment/prod/vaec-celery-task-definition.json
cd/application-deployment/staging/vaec-api-task-definition.json
cd/application-deployment/staging/vaec-celery-beat-task-definition.json
cd/application-deployment/staging/vaec-celery-task-definition.json
ci/Dockerfile.datadog

This PR does the following:
1. Updates the datadog Dockerfile to require a version tag to be passed in.
2. Updates the Github Action that mirrors the Datadog image to require the version tag to be passed in, which then passes it to the Dockerfile
3. Uses the newest datadog agent version 7.57.2 in all envs
I changed the way we do this because using the `latest` tag throughout the process introduces a lot of risk now that we autoscale Celery tasks. Imagine a scenario where we update the DD image in ECR and tag it as `latest` (which the old workflow was doing) and shortly after Celery tasks start scaling up. Those new Celery tasks would be using an untested version of the Datadog agent in prod.
This new change to the Dockerfile and the workflow requires us to pass through the version tag we …

TEAM-1379 - Modify datadog dockerfile and workflow to take version tag as input

---

app/clients/sms/twilio.py
app/va/va_profile/va_profile_client.py

This is causing the following error when the error code variable is not set when logging the message from Twilio. It's causing the `process-delivery-status-result` celery task to fail in this case.
```
File "/app/app/clients/sms/twilio.py", line 265, in translate_delivery_status
error_code,
UnboundLocalError: local variable 'error_code' referenced before assignment
```
issue N/A

HOTFIX - Fix UnboundLocalError in Twilio Client

---

migrations/versions/0373_va_profile_cache_notification_id.py
migrations/versions/0373_va_profile_notification.py

issue #1979 
- This ticket requires that the `notification_id` from the send Comp and Pen Opt-In confirmation be saved to the `va_profile_local_cache` table. 
- I am doing the migration work as a separate PR to make deploying and reviewing easier.
- [The rest of the work will be finished in this ticket. ](https://github.com/department-of-veterans-affairs/notification-api/pull/2056)

#1979 - add notification column to VA Profile Local Cache

---

.github/scripts/prData.js
.github/workflows/cd-pipeline.yml
.github/workflows/deploy-release.yml

This PR fixes a bug where the CD pipeline would tag the latest main instead of tagging the commit sha that triggered the pipeline. This caused confusion with what was being sent up to production in our pipeline and generating incorrect release notes.
The fix in this PR is to have our tagging script take in the ref being tagged instead of defaulting to `origin/main`.
I tested this with @cris-oddball. We triggered the CD pipeline form my branch, specifically from the SHA 13f62e440e2b55fc43870da139ac70d915e31ddc.
The new tag being generated:
The SHA tied to the tag:

HOTFIX - Use the merge commit when cutting a tag for release

---

.github/workflows/cd-pipeline.yml

This PR removes the approval to production step in our CD pipeline. With anomaly detection in place, we have reached a point where we feel comfortable automating our CD process to production.
issue #2086 
It's difficult to test this since this is a change to a production step in our CD process. There isn't a lower environment to test this in. I'm confident that this will work, as it is just removing one step.

#2096 - Remove approval to production step in CD pipeline

---

app/models.py
migrations/versions/0374_add_expected_cadence.py

Adds the `expected_cadence` text field to the `promoted_templates` table
issue [2480](https://github.com/orgs/department-of-veterans-affairs/projects/1415/views/1?pane=issue&itemId=84874824&issue=department-of-veterans-affairs%7Cnotification-portal%7C2480) of the notification-portal
ran `flask db upgrade` and then `flask db downgrade` locally
[deploy to dev - api action run successful](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11843301849) - verifies migration run successfully
[DB downgrade action run successful](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11843979399) - verifies migration rollback successful
- [na] I have added tests that prove my fix is effective or that my feature works. [Testing …

PORTAL-2480 - creates migration to add expected_cadence to promoted_templates

---

.talismanrc
app/celery/provider_tasks.py
tests/README.md
tests/app/celery/test_provider_tasks.py

We want a more descriptive "status_reason" for SMS notifications that fail permanently due to the recipient having opted-out.  I wrote a new unit test for the changes.  The test mocks out a lot of downstream code, but I don't see an easy way not to mock given the layers of downstream code.
I also revised the testing README.md, which was not well organized.
issue #2092
I deployed API Dev.  All unit and regression tests pass.  @cris-oddball sent an SMS notification to an opted-out number and inspected the results with Postman and in DD.  We observed the expected behavior.
This is the error message returned from Pinpoint:
This is the "status_reason" recorded in our database:

#2092 opt out status reason

---

cd/application-deployment/prod/vaec-celery-task-definition.json

A hot, hot fix.  [Memory in PROD spiking.](https://us-gov-west-1.console.amazonaws-us-gov.com/ecs/v2/clusters/prod-notification-cluster/services/prod-notification-celery-service/health?region=us-gov-west-1) 
Increasing PROD ECS Celery service Memory  from 4096 to 8192. 
Keep CPU at 2048

HOT FIX - #2041 increase prod ecs celery service memory

---

.github/workflows/cd-pipeline.yml
.github/workflows/create-and-post-tag.yml
.github/workflows/create-release-notes.yml
.github/workflows/db-downgrade.yml
.github/workflows/dependency-ticket-creation.yml
.github/workflows/deploy-release.yml
.github/workflows/deploy_lambda_dev.yml
.github/workflows/deployment.yml
.github/workflows/dev-tests.yml
.github/workflows/dev_deploy.yml
.github/workflows/lambda-functions.yml
.github/workflows/load-test-email-delivery-time.yaml
.github/workflows/load-test-sms-response-time.yaml
.github/workflows/pr-label-semver.yml
.github/workflows/pre-tag-summary.yml
.github/workflows/publish-release-notes.yml
.github/workflows/run-regression.yml
.github/workflows/twistlock.yml
.github/workflows/update-datadog-image.yaml

Modified `runs-on` to use a plaintext repo variable so we can set it once, everywhere. Easy to update whenever we need. After verifying 24.04 works we can change it to ubuntu-latest for all.
issue #2157 
Pushed then kicked off a [Deploy Lambdas to Env Action](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/12166270959/job/33932126837#step:1:8) to verify it grabbed the variable and used it properly.
Deployed with the updated action:

#2157 - Updated Github Action runs-on

---

app/celery/common.py
tests/app/celery/test_common.py

Twilio delivery status can come in with a negative timestamp due to only having minute granularity. This only affects our logging but has been updated so our internal charts and logs are not confusing.
issue #2159 
Wrote a new test. Deployed.
Ran requests using Twilio at various times to attempt to trigger a negative number, all were positive:

#2159 - Update Total Time For Twilio Delivery Status 

---

.github/workflows/dependency-ticket-creation.yml

The cron implementation was set to run only on Monday's that were also the 14th day of the month 🤦 . This hotfix makes the cron run every week on a Monday regardless of the date. Github Actions does not have a native way to specify every 2 weeks with cron, and since we check if a ticket is already created before creating a new one, I'm comfortable having this run once per week.
The ticket creation portion works, but the cron was set to a schedule that would likely never run. We will have to wait until next Monday to make sure it kicks off.

HOTFIX - Fix dependency ticket cron to run every week

---

.talismanrc
documents/openapi/openapi.yaml

- Updating the Swagger documentation to note  o indicate that email notifications can now include personalization rendered as a bullet list.
- Includes examples in documentation
issue #2082 
- Confirmed updated doc with with @kbelikova-oddball

#2082 -  Update Swagger for Bulleted List in Emails

---

.talismanrc
app/dao/api_key_dao.py
tests/app/dao/test_api_key_dao.py

- Updating api key generation
Issue [#TEAM-1420](https://github.com/orgs/department-of-veterans-affairs/projects/1417/views/1?pane=issue&itemId=86393283&issue=department-of-veterans-affairs%7Cvanotify-team%7C1420)
[Deployed to DEV OK](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/12317437790)

TEAM-1420 - Updating API Key generation

---

.talismanrc
app/models.py
tests/app/test_model.py
tests/app/v2/notifications/test_get_notifications.py

This PR redacts the `personalisation` field in the serialized Notification responses. A GET request to `v2/notifications/` will return the literal `<redacted>` in place of the personalization fields. 
issue #1357 
This was [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/12318271329/job/34383134676) and tested in perf -
- sent a SMS using a template that had a personalization field, note the `((variable))`, in `content`.
- Issued a GET to v2/notifications/sms, note that `body` is `<redacted>`
- Verified on my phone that the SMS had the correct personalization (`dolore rebum`)
- Redeployed to dev and tested email subject redaction
The unit tests cover emails, and have slightly more personalization fields.

#1357 Redact Personalization in Serialized Notifications

---

app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

This PR redacts personalization in POST responses to `/v2/notifications`, a follow up to [this PR](https://github.com/department-of-veterans-affairs/notification-api/pull/2180).
issue #1357 
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/pull/2180)
- Sent an email, the POST response has been redacted:

#1357 - Redact personalization in POST responses

---

.github/workflows/cd-pipeline.yml
.github/workflows/dev_deploy.yml

This PR adds a conditional to the deploy to production step in our CD pipeline. The conditional is keying in the repository environment variable `CODE_FREEZE`.
issue #2195 
I had @k-macmillan set the env var to false and ran the deploy to dev workflow. I then had him set the env var to true and ran the workflow again. Below are the results.
Set `CODE_FREEZE` to false and tested in dev:
Set `CODE_FREEZE` to true and tested in dev:

HOTFIX - Add code freeze conditional to production deploy in CD pipeline

---

lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py

These changes update logging for the Vetext forwarder lambda to bring it into compliance with our logging document.  Note that using `logger.exception` logs at the "Error" level and includes the stack trace in the output.
issue #1497
I deployed the branch with lambdas and let the regressions run.

#1497 Update logging for the Vetext forwarder lambda

---

.github/workflows/task-defnition-cleanup.yaml

This PR introduces a GHA workflow that deregisters all api and celery task definitions except the most recent 10 (for each family). The workflow runs on a cron, every Sunday at 00:00 UTC. There is also a workflow dispatch option that contains a dry run for testing purposes.
issue [TEAM 1177](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1177)
As of right now, only dry run has been tested. I am going to test this now without dry run, and I am expecting it to fail on API limits being hit in AWS. Failed workflows on API limits are acceptable for now while we churn through the thousands of task definitions we have to deregister.
Once we churn through those, running this weekly should not trigger API limits.
Dry run: …

TEAM #1177- Add script to cleanup task definitions in GHA workflow

---

app/clients/sms/aws_pinpoint.py
app/clients/sms/twilio.py
tests/app/celery/test_process_delivery_status_result_tasks.py

Saw some oddities with Twilio outputs and was able to track it down as a non-issue but would have been much easier with this kind of logging.
issue N/A
Deployed, observed output. Used safe lookups to perform redaction where necessary.

HOTFIX - SMS Pre-Translate Logging

---

cd/application-deployment/perf/vaec-celery-task-definition.json

Celery task on Friday OOM'd, so we are going to bump this task from 4GB of memory to 5GB. I'm opting for a smaller jump because the average memory remained at around 50% utilization, but maximum jumped up and killed the task. If we need more we can always add more.
Config change, nothing to test.

HOTFIX - Bumps memory of celery task in perf

---

.github/actions/build-push-artifacts/action.yml
.github/workflows/db-downgrade.yml
.github/workflows/deploy-release.yml
.github/workflows/deployment.yml
.github/workflows/dev_deploy.yml
.github/workflows/lambda-functions.yml
.github/workflows/load-test-email-delivery-time.yaml
.github/workflows/load-test-sms-response-time.yaml
.github/workflows/task-defnition-cleanup.yaml
.github/workflows/twistlock.yml
.github/workflows/update-datadog-image.yaml

https://github.com/department-of-veterans-affairs/notification-api/issues/2229
This PR serves two purposes:
1. Loosely pin the Github action `configure-aws-credentials` to v4 instead of hard pinning it to 4.0.2.
2. Getting notification API reconciled post code freeze.
This PR is being set to a minor version update to make sure that all of the changes that were merged during the holiday code freeze are packaged nicely into a minor version bump. Following the merging of this PR, @cris-oddball will organize and update release notes to accurately reflect the set of changes going out to production.
The dev deploy being successful is a sufficient test.

HOTFIX - Loosely pin configure-aws-credentials to v4

---

app/celery/provider_tasks.py
app/clients/sms/twilio.py
tests/app/clients/test_twilio.py

Updates the catch to raise a `RetryableException`, and upstream we catch avoid logging it as an exception because it is logged where the exception happened. 
Catches this [exception](https://vanotify.ddog-gov.com/logs?query=%40exc_info%3A%2ATwilioRestException%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZRArEiOAAA2n_jCueMvJwAb&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Cdesc&viz=&from_ts=1736011556047&to_ts=1736270756047&live=false) now:
Also put the `ConnectionError`, `ConnectTimeout`, and `ReadTimeout` that was falling into the [generic catch and retry](https://vanotify.ddog-gov.com/logs?query=%22Twilio%20send%20SMS%20request%20for%22%20%22failed%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice …

#2219 - TwilioRestException Retry Logging

---

.talismanrc
app/celery/process_ses_receipts_tasks.py
app/dao/notifications_dao.py
tests/app/celery/test_process_delivery_status_result_tasks.py
tests/app/celery/test_process_pinpoint_receipt_tasks.py
tests/app/celery/test_process_ses_receipts_tasks.py

This PR redacts personalization in the database when a notification is in a final state.
issue #1358 
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/13011771326), unit and regression tests pass.
- Sent an SMS with personalization
Verified:
- rendered correctly on phone. 
- field is encrypted and redacted in Postgres
- Sent an email with personalization
Verified:
- rendered correctly
- field is encrypted and redacted in Postgres

#1358 Redact personalization when in final state

---

.talismanrc
app/notifications/process_notifications.py
app/template/rest.py
app/utils.py
app/v2/template/post_template.py
poetry.lock
pyproject.toml
tests/app/celery/test_tasks.py
tests/app/notifications/test_process_notifications.py

These changes add unit tests and pull in an updated version of Utils.  (See the Utils PR.)  The goal is that requests to send e-mail using a template with a placeholder in the subject return 400 if the POST data doesn't contain an associated value.  The problem was that Utils was only checking for missing values in the content body.
- issue #2286
- Associated [Utils PR](https://github.com/department-of-veterans-affairs/notification-utils/pull/205).
I repeated that steps in the ticket to reproduce the problem and observed that it's no longer a problem.
Happy path with template `b2c9ff49-b37b-4352-ab0c-3d3d0710fe4c`:
Missing subject data:
Missing content data:
Missing subject data with template `64b0953c-b7ea-4b48-b70f-d242ce5b17d2`, which only has a placeholder in the subject:

#2286 missing e-mail subject personalisation errors

---

.talismanrc
app/models.py
tests/app/test_model.py
tests/app/v2/notifications/test_get_notifications.py

These changes:
- Modify the Notification.serialize method to use the value "\<redacted\>" for ICNs
- Replace the use of "create_notification" with "sample_notification" in the test file tests/app/v2/notifications/test_get_notifications.py (tech debt removal)
issue [team-1455](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1455)
Notification `ef037299-52c4-424c-acbb-96beb02ef065` has an associated VA Profile ID and ICN.  Without these changes, the GET response includes:
```
"recipient_identifiers": [
{
"id_type": "VAPROFILEID",
"id_value": "43627"
},
{
"id_type": "ICN",
"id_value": "...(THIS WAS NOT REDACTED)..."
}
],
```
I manually redacted id_value above.  With these changes for redaction:
```
"recipient_identifiers": [
{
"id_type": "VAPROFILEID",
"id_value": …
```

#Team-1455 ICN redaction

---

app/celery/send_va_profile_notification_status_tasks.py
app/va/va_profile/va_profile_client.py
tests/app/celery/test_send_va_profile_notification_status_tasks.py

Include the service name in the callback payload sent to VA Profile.
issue #2063
Profile team member Ian McEwan found the above notification in their logs with this payload:
```json
{"id": "9da1c324-b701-450b-928a-f51e0da0d64a", "reference": null, "to": "<my e-mail address>", "status": "delivered", "status_reason": null, "created_at": "2025-02-13T19:04:53.221849Z", "completed_at": "2025-02-13T19:04:55.639176Z", "sent_at": "2025-02-13T19:04:53.716212Z", "notification_type": "email", "provider": "ses", "service_name": "VA Notify"}
```
Note the "service_name" attribute.

#2063 - Service name in callback

---

app/googleanalytics/ga4.py

Any [Celery calls](https://docs.celeryq.dev/en/stable/userguide/calling.html#basics) (such as `delay` or `apply_async`) are at risk of throwing an exception and should be caught. This is a temporary solution so we can track down why this is happening. Error logs are regularly scanned, so a follow on ticket will be made at that time to fix the issue and restructure the function to avoid nested try/except blocks.
Future work may need to use [signal](https://docs.python.org/3/library/signal.html#signal.alarm) to abort Celery delay/apply_async if it is taking too long.
issue #2315 
This was deployed, but there's no way to force this. It's an intermittent failure, so cannot be reproduced. Just looking to catch and exception log it.

#2315 - Catch and Log Celery Task Exceptions

---

.talismanrc
app/models.py
migrations/versions/0376_drop_reply_to.py
tests/app/conftest.py
tests/app/db.py
tests/conftest.py

These changes:
- Remove the table ServiceEmailReplyTo, which is unused in production. (Do not remove the table ReplyToInbox, which Portal uses.) There is an associated migration.
- Remove or modify associated test fixtures.
issue #1112
Note that this PR is "part 2 of 2."  I tested the migration downgrade before I split work for this ticket into two PRs, and I don't think it's necessary to retest this.  It's the exact same migration as before.

#1112 - Drop the ServiceEmailReplyTo table (part 2 of 2)

---

gunicorn_config.py

We are seeing [gunicorn timing out](https://vanotify.ddog-gov.com/logs?query=host%3Aprod-notification-api-log-group%20service%3Acloudwatch%20%40aws.awslogs.logGroup%3Aprod-notification-api-log-group&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&context_event=AZUgzCJnAAAYv9VGdHArDQEV&event=&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Cdesc&to_event=AwAAAZUgzBDweEivJwAAABhBWlVnekNKbkFBQVl2OVZHZEhBckRRQ28AAAAkMDE5NTIwZDAtYTZkMS00NmIyLTlhZWQtY2QzYWVmYjZjZjc0AADHwQ&viz=&from_ts=1740011699472&to_ts=1740011999473&live=false). This appears to be related to Celery apply_async/delay. In the short-term we will extend the timeout, long term we need to identify why this is happening.
[Default is 30 …

HOTFIX - Gunicorn Timeout

---

app/models.py
documents/openapi/openapi.yaml
migrations/versions/0377_template_content.py
tests/app/v2/template/test_get_template.py

These changes:
- Add the "content_as_html" and "content_as_plain_text" fields to the TemplateBase model class, which adds those fields in the database to the "templates" and "templates_history" tables
- As a consequence, the template serializers automatically add these new fields in the responses of the routes identified in the ticket's "acceptance criteria" section.  I updated the Swagger spec to reflect this.
This is to support future work.  Currently, when sending a notification with a given template, we always convert the template's markdown to HTML or plain text, but this output is constant unless users change the markdown.  We shouldn't need to perform the computation for every notification.
issue #2278
```sh
notification_api=# \d templates
Table "public.templates"
Column …
```

#2278 Add HTML and plain text fields to TemplateBase

---

app/celery/process_ses_receipts_tasks.py
app/notifications/notifications_ses_callback.py
tests/app/celery/test_process_ses_receipts_tasks.py
tests/app/conftest.py
tests/app/notifications/test_notifications_ses_callback.py

Paired with Kyle to trace the error/exception paths.
Complexity metric increased.
Iterated the changes, updating failing unit tests.
1. Address errors resulting in exception handler throwing UnboundLocal
2. Ensure sample_notification_history has a valid reference, uuid4
3. Moved notification lookup out to main celery task to ensure notification available to exception handlers
4. Added KeyError handler to handle malformed payloads
5. Updated unittests for change function signatures
6. Added coverage for missing/None reference but update to sample_notification_history should fix this in tests.
7. Added test for notification not found (forcing no retry to catch error message)
issue #803 
Unit testing and DEV deploy regression tests.

#803 - Hotfix - resolve unbound variable and exception handling

---

.talismanrc
app/dao/api_key_dao.py
app/service/rest.py
documents/openapi/openapi.yaml
tests/app/dao/test_api_key_dao.py
tests/app/service/test_api_key_endpoints.py
tests/app/service/test_rest.py

This PR enhances API key retrieval by filtering keys based on their expiry date and revocation status. Key changes include:
- Updating the API endpoint in rest.py to parse a new query parameter, include_revoked, which controls whether revoked (and thus expired) keys are returned.
- Revising the DAO method get_model_api_keys to support the include_revoked flag while filtering out revoked API keys by default.
- Adjusting tests in both the service and DAO layers to reflect the updated expected key counts and behavior.
issue #2311
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/13833195053)
- Tested with Postman against dev.
- with no `include_revoked` param
- with `include_revoked=true`, there were too many results for the preview, had to …

#2311 - API Key Revoked Filter 

---

README.md
app/internal/rest.py
tests/app/internal/test_rest.py

Update GET response for internal testing endpoint to return JSON object containing response string.
POST route was not altered.
Logging messages have not been changed.
TEAM-1487 - Code Scan
https://github.com/department-of-veterans-affairs/vanotify-team/issues/1487
Updated unit testing to reflect new response structure
Tested locally with CURL
**Before**
`curl -X GET "http://127.0.0.1:6011/internal/test?param1=100&param2=\"bob\"" -w "\n"`
`GET request received for endpoint /internal/test?param1=100&param2="bob"`
**After**
`curl -X GET "http://127.0.0.1:6011/internal/test?param1=100&param2=\"bob\"" -w "\n"`
```
{
"test": "GET request received for endpoint /internal/test?param1=100&param2=\"bob\""
}
```
https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/138431 …

TEAM-1487 - Code scan

---

.github/actions/build-push-artifacts/action.yml
.github/workflows/dev-tests.yml
ci/Dockerfile
ci/docker-compose-ci.yml

This PR implements Docker caching during unit testing (CI). It does this by adapting https://docs.docker.com/build/cache/backends/gha/ a little bit, because we use docker-compose to run our tests in CI.
At a high level, this PR:
1. Sets up buildx (requirement) to allow us to use the GHA backend cache store
2. Sets up the GHA runtime on the host to allow us to use buildx
3. Performs the build and caching
**NOTE**: This feature is listed as experimental on GHA documentation, but it is also listed as the recommended approach to caching docker images between runs. According to [GHA cache usage limits](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy), it will delete unused caches …

#2357 - Implement docker build caching

---

app/celery/provider_tasks.py
app/va/mpi/mpi.py
tests/app/celery/test_provider_tasks.py

There's an SMS use case that is stuck on a lower MPS. The sms sender is set to rate limit but the value was not properly adjusted. Did testing in dev to understand what should be set in prod and found the rate limit code was lacking.
Also adjusted some log outputs because they were at risk of logging data that we would prefer to keep out of logs.
issue N/A
Unit tested locally. GHA, [deploy + regression](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15008477125).
Sent 20 requests using a rate-limited sms_sender. The rate_limit_interval was set to 37 seconds.
Works exactly as expected. It retried 134 times, but they were spread out.  The prod case that started this retried thousands of times for just 65 or so notifications.

HOTFIX - Sender Rate Limit and ICN Updates

---

app/dao/inbound_numbers_dao.py
app/inbound_number/rest.py
tests/app/dao/test_inbound_numbers_dao.py
tests/app/inbound_number/test_rest.py

This PR adds error handling when attempting to deactivate an inbound number that doesn't exist by updating the DAO to raise a ValueError and modifying the REST endpoint to catch that error and return a 400 response.
issue #1575 
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15114806328)
- POST to the inbound number deactivate endpoint with an invalid uuid (I used the sms_template_id var).
``` http
POST /vanotify/inbound-number/463a744a-bfcb-4044-af27-e8d6c6f092bd/off HTTP/1.1
Content-Type: application/json
Accept: */*
HTTP/1.1 400 BAD REQUEST
Date: Mon, 19 May 2025 13:07:46 GMT
Content-Type: application/json
Content-Length: 162
{
"errors": [
{
"error": "BadRequestError",
"message": "Inbound number with id …
```

#1575 bugfix-deactivating-nonexistent-inbound-number

---

.github/workflows/task-defnition-cleanup.yaml
.github/workflows/update-datadog-image.yaml

This PR removes the default GHA permissions from two workflows: Datadog image updated and ECS task def cleanup. This is part of a larger initiative to scope down our GHA workflows.
TEAM-1633
Successfully tested the ECS task definition workflow.
Did not test the datadog image updater, but it does not perform any actions to Github resources. When we run the updater the next time we update our DD image, if it fails, I will fix it.

Remove default permissions from DD and task def workflows

---

.talismanrc
app/constants.py
app/dao/api_key_dao.py
app/schemas.py
app/service/rest.py
tests/app/dao/test_api_key_dao.py
tests/app/service/test_api_key_endpoints.py
tests/app/service/test_secret_generator.py

This PR adds support for generating API keys with a UUID-style secret while maintaining backward compatibility for existing secret-generation behavior. 
issue #2261 
- [Deployed to dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/15348118726)
- Fired off some Postman requests, they are all api secrets so I can't really post here. I did a backwards-compatibility test and tested the new payload.

#2261 - API Key generation allows uuid type
